#!/usr/bin/env bash
# install.sh -- Install Agent Historic persona rules into AI coding editors
# Run from the project root: bash install.sh [--claude] [--cursor] [--windsurf] [--codex] [--opencode] [--all]
# Use --gpt to install sparse/GPT-optimized rules for Cursor and Windsurf instead of rich
# No flags = auto-detect installed editors

set -e

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"

# --- Source directories (generated by: node scripts/build-prompt-system.mjs) ---
SRC_CLAUDE="$REPO_DIR/compiled/claude/rules"
SRC_CURSOR="$REPO_DIR/compiled/cursor/rules"
SRC_CURSOR_GPT="$REPO_DIR/compiled/cursor/rules/gpt"
SRC_WINDSURF="$REPO_DIR/compiled/windsurf/rules"
SRC_WINDSURF_GPT="$REPO_DIR/compiled/windsurf/rules/gpt"
SRC_CODEX="$REPO_DIR/compiled/codex"
SRC_OPENCODE="$SRC_CLAUDE"

# --- Target directories (user home) ---
DEST_CLAUDE="$HOME/.claude/rules"
DEST_CURSOR="$HOME/.cursor/rules"
DEST_WINDSURF="$HOME/.windsurf/rules"
DEST_CODEX="$HOME/.codex"
DEST_OPENCODE="$HOME/.config/opencode/rules"

# --- Managed-file marker (used for stale cleanup) ---
MANAGED_MARKER="managed_by: agent-historic"

cleanup_managed_files() {
  local dest_dir="$1"
  [[ -d "$dest_dir" ]] || return 0
  while IFS= read -r -d '' f; do
    rm "$f"
    echo "    Removed stale: $f"
  done < <(grep -rlZ "$MANAGED_MARKER" "$dest_dir" 2>/dev/null)
}

# --- Backup ---

backup_dir() {
  local dir="$1"
  if [[ -d "$dir" ]]; then
    local ts
    ts="$(date +%Y%m%d-%H%M%S)"
    cp -r "$dir" "${dir}-${ts}"
    echo "    Backup: ${dir}-${ts}"
  fi
}

# --- Loader-header injection ---
# Writes (or replaces) a marked block at the top of a file that tells the IDE
# to always load the init + router rules. Idempotent: re-runs replace the block.
MARKER_BEGIN="<!-- agent-historic:loader-begin -->"
MARKER_END="<!-- agent-historic:loader-end -->"

inject_loader_header() {
  local file="$1"
  local rules_dir="$2"
  local title="$3"

  local block
  block="$(cat <<HEADER
$MARKER_BEGIN
# $title

Always load and apply the following rule files from \`$rules_dir\` at the start of every conversation:

1. \`$rules_dir/00-init.md\` — Global runtime (constraints, logging, voice, definition of done)
2. \`$rules_dir/01-router.md\` — MoE router (expert selection, pipelines, disambiguation)

These two files are always active. All other expert files in \`$rules_dir\` are activated by model decision based on their description field.
$MARKER_END
HEADER
)"

  if [[ -f "$file" ]]; then
    if grep -q "$MARKER_BEGIN" "$file" 2>/dev/null; then
      # Replace the existing block between markers (inclusive)
      local tmp
      tmp="$(mktemp)"
      BLOCK="$block" MARKER_BEGIN="$MARKER_BEGIN" MARKER_END="$MARKER_END" TARGET_FILE="$file" python3 <<'PY' > "$tmp"
import os
from pathlib import Path

path = Path(os.environ["TARGET_FILE"])
content = path.read_text()
begin = os.environ["MARKER_BEGIN"]
end = os.environ["MARKER_END"]
block = os.environ["BLOCK"]

start = content.find(begin)
finish = content.find(end, start if start != -1 else 0)

if start != -1 and finish != -1:
    finish += len(end)
    if finish < len(content) and content[finish:finish + 1] == "\n":
        finish += 1
    updated = content[:start] + block + "\n" + content[finish:]
else:
    updated = block + "\n\n" + content

print(updated, end="")
PY
      mv "$tmp" "$file"
    else
      # Prepend block to existing content
      local tmp
      tmp="$(mktemp)"
      { echo "$block"; echo ""; cat "$file"; } > "$tmp"
      mv "$tmp" "$file"
    fi
  else
    mkdir -p "$(dirname "$file")"
    echo "$block" > "$file"
  fi
  echo "    Loader:   $file"
}

# --- Install functions ---

install_claude() {
  mkdir -p "$DEST_CLAUDE"
  cleanup_managed_files "$DEST_CLAUDE"
  for f in "$SRC_CLAUDE"/*.md; do
    [[ -f "$f" ]] || continue
    cp "$f" "$DEST_CLAUDE/$(basename "$f")"
    echo "    Claude:   $DEST_CLAUDE/$(basename "$f")"
  done
  inject_loader_header "$HOME/.claude/CLAUDE.md" "~/.claude/rules" "Claude Code Instructions"
}

install_cursor() {
  mkdir -p "$DEST_CURSOR"
  cleanup_managed_files "$DEST_CURSOR"
  # Rich rules at root (universal default)
  for f in "$SRC_CURSOR"/*.mdc; do
    [[ -f "$f" ]] || continue
    cp "$f" "$DEST_CURSOR/$(basename "$f")"
    echo "    Cursor:   $DEST_CURSOR/$(basename "$f")"
  done
  # GPT/sparse rules (only with --gpt)
  if [[ "$USE_GPT" == true ]]; then
    mkdir -p "$DEST_CURSOR/gpt"
    for f in "$SRC_CURSOR_GPT"/*.mdc; do
      [[ -f "$f" ]] || continue
      cp "$f" "$DEST_CURSOR/gpt/$(basename "$f")"
      echo "    Cursor:   $DEST_CURSOR/gpt/$(basename "$f") (sparse/deprecated)"
    done
  fi
}

install_windsurf() {
  mkdir -p "$DEST_WINDSURF"
  cleanup_managed_files "$DEST_WINDSURF"
  # Rich rules at root (universal default)
  for f in "$SRC_WINDSURF"/*.md; do
    [[ -f "$f" ]] || continue
    cp "$f" "$DEST_WINDSURF/$(basename "$f")"
    echo "    Windsurf: $DEST_WINDSURF/$(basename "$f")"
  done
  # GPT/sparse rules (only with --gpt)
  if [[ "$USE_GPT" == true ]]; then
    mkdir -p "$DEST_WINDSURF/gpt"
    for f in "$SRC_WINDSURF_GPT"/*.md; do
      [[ -f "$f" ]] || continue
      cp "$f" "$DEST_WINDSURF/gpt/$(basename "$f")"
      echo "    Windsurf: $DEST_WINDSURF/gpt/$(basename "$f") (sparse/deprecated)"
    done
  fi
}

install_codex() {
  mkdir -p "$DEST_CODEX"
  cleanup_managed_files "$DEST_CODEX"
  cp -r "$SRC_CODEX"/* "$DEST_CODEX/"
  echo "    Codex:    $DEST_CODEX/"
}

install_opencode() {
  mkdir -p "$DEST_OPENCODE"
  cleanup_managed_files "$DEST_OPENCODE"
  for f in "$SRC_OPENCODE"/*.md; do
    [[ -f "$f" ]] || continue
    cp "$f" "$DEST_OPENCODE/$(basename "$f")"
    echo "    OpenCode: $DEST_OPENCODE/$(basename "$f")"
  done
  inject_loader_header "$HOME/.config/opencode/AGENTS.md" "~/.config/opencode/rules" "Agent Instructions"
}

# --- List functions ---

list_claude() {
  echo "    Claude (~/.claude/rules/):"
  for f in "$SRC_CLAUDE"/*.md; do
    [[ -f "$f" ]] || continue
    local name
    name="$(basename "$f")"
    local dest="$DEST_CLAUDE/$name"
    local status="not found"
    [[ -f "$dest" ]] && status="installed"
    echo "      $dest  [$status]"
  done
}

list_cursor() {
  echo "    Cursor (~/.cursor/rules/):"
  for f in "$SRC_CURSOR"/*.mdc; do
    [[ -f "$f" ]] || continue
    local name
    name="$(basename "$f")"
    local dest="$DEST_CURSOR/$name"
    local status="not found"
    [[ -f "$dest" ]] && status="installed"
    echo "      $dest  [$status]"
  done
}

list_windsurf() {
  echo "    Windsurf (~/.windsurf/rules/):"
  for f in "$SRC_WINDSURF"/*.md; do
    [[ -f "$f" ]] || continue
    local name
    name="$(basename "$f")"
    local dest="$DEST_WINDSURF/$name"
    local status="not found"
    [[ -f "$dest" ]] && status="installed"
    echo "      $dest  [$status]"
  done
}

list_codex() {
  echo "    Codex (~/.codex/):"
  local dest="$DEST_CODEX/AGENTS.md"
  local status="not found"
  [[ -f "$dest" ]] && status="installed"
  echo "      $dest  [$status]"
}

list_opencode() {
  echo "    OpenCode (~/.config/opencode/rules/):"
  for f in "$SRC_OPENCODE"/*.md; do
    [[ -f "$f" ]] || continue
    local name
    name="$(basename "$f")"
    local dest="$DEST_OPENCODE/$name"
    local status="not found"
    [[ -f "$dest" ]] && status="installed"
    echo "      $dest  [$status]"
  done
  local agents="$HOME/.config/opencode/AGENTS.md"
  local astatus="not found"
  [[ -f "$agents" ]] && astatus="installed"
  echo "      $agents  [$astatus]"
}

# --- Auto-detection ---

detect_editors() {
  local detected=()
  [[ -d "$HOME/.claude" ]] && detected+=("claude")
  [[ -d "$HOME/.cursor" ]] && detected+=("cursor")
  [[ -d "$HOME/.windsurf" || -d "$HOME/.codeium/windsurf" ]] && detected+=("windsurf")
  [[ -d "$HOME/.codex" ]] && detected+=("codex")
  [[ -d "$HOME/.config/opencode" ]] && detected+=("opencode")
  echo "${detected[@]}"
}

# --- Post-install notes ---

print_post_install() {
  echo ""
  echo "=== POST-INSTALL: REQUIRED IDE CONFIGURATION ==="
  echo ""
  if [[ "$SCAFFOLDED_MODE" == true ]]; then
    echo "  Voice: scaffolded (externalized reasoning with explicit labels)."
  else
    echo "  Voice: calibrated (internalized, peer-like prose)."
  fi
  echo "  Rich rules are installed as the universal default for all models."
  if [[ "$USE_GPT" == true ]]; then
    echo "  Sparse/GPT rules also installed in gpt/ subfolder (deprecated)."
  fi
  echo ""

  for target in "$@"; do
    case "$target" in
      claude)
        echo "  Claude Code"
        echo "    Rules installed to ~/.claude/rules/."
        echo "    CLAUDE.md loader header injected into ~/.claude/CLAUDE.md."
        echo "    No extra config needed."
        echo ""
        ;;
      cursor)
        echo "  Cursor (IMPORTANT)"
        echo "    1. Open Cursor Settings > Rules for AI"
        echo "    2. 00-init must load on every request (alwaysApply: true)."
        echo "    3. 01-router must load on every request (alwaysApply: true)."
        echo "    4. Expert rules (expert-*.mdc) are auto-attached by Cursor"
        echo "       when their description matches the conversation context."
        echo "    Files: ~/.cursor/rules/"
        echo ""
        ;;
      windsurf)
        echo "  Windsurf (IMPORTANT)"
        echo "    1. Open Windsurf > Customizations > Rules"
        echo "    2. 00-init.md has trigger: always — global runtime."
        echo "    3. 01-router.md has trigger: always — request triage."
        echo "    4. Expert rules use trigger: model_decision — Cascade reads"
        echo "       them automatically when the description matches."
        echo "    Files: ~/.windsurf/rules/"
        echo ""
        ;;
      codex)
        echo "  Codex"
        echo "    AGENTS.md and skills/ are installed to ~/.codex/."
        echo "    No extra config needed."
        echo ""
        ;;
      opencode)
        echo "  OpenCode"
        echo "    Rules installed to ~/.config/opencode/rules/."
        echo "    AGENTS.md loader header injected into ~/.config/opencode/AGENTS.md."
        echo "    No extra config needed."
        echo ""
        ;;
    esac
  done

  echo "  Tip: Run 'bash install.sh --list' to verify installed files."
  echo ""
}

# --- CLI parsing ---

TARGETS=()
DO_LIST=false
USE_GPT=false
DEBUG_MODE=false
SCAFFOLDED_MODE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --claude)    TARGETS+=("claude"); shift ;;
    --cursor)    TARGETS+=("cursor"); shift ;;
    --windsurf)  TARGETS+=("windsurf"); shift ;;
    --codex)     TARGETS+=("codex"); shift ;;
    --opencode)  TARGETS+=("opencode"); shift ;;
    --all)       TARGETS=("claude" "cursor" "windsurf" "codex" "opencode"); shift ;;
    # --gpt installs deprecated sparse rules alongside rich (opt-in)
    --gpt)       USE_GPT=true; shift ;;
    --list)      DO_LIST=true; shift ;;
    --debug)     DEBUG_MODE=true; shift ;;
    --scaffolded) SCAFFOLDED_MODE=true; shift ;;
    --help|-h)
      echo "Usage: bash install.sh [options]"
      echo ""
      echo "Options:"
      echo "  --claude       Install rules for Claude Code"
      echo "  --cursor       Install rules for Cursor"
      echo "  --windsurf     Install rules for Windsurf"
      echo "  --codex        Install rules for Codex"
      echo "  --opencode     Install rules for OpenCode"
      echo "  --all          Install for all editors"
      echo "  --gpt          [DEPRECATED] Also install sparse/GPT-optimized rules in gpt/ subfolder"
      echo "                 Rich rules are now the universal default for all models."
      echo "  --list         List installed files and their status (no changes made)"
      echo "  --scaffolded   Use scaffolded voice (externalized reasoning with HYPOTHESIS/VERIFIED labels)"
      echo "                 Default is voice-calibrated (internalized, peer-like prose)."
      echo "  --debug        Include self-identification routing preamble in generated rules"
      echo "  -h, --help     Show this help"
      echo ""
      echo "No flags = auto-detect installed editors."
      echo ""
      echo "Before running, generate the prompt files:"
      echo "  node scripts/build-prompt-system.mjs"
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      echo "Run: bash install.sh --help"
      exit 1
      ;;
  esac
done

# --- Build ---

if [[ -f "$REPO_DIR/scripts/build-prompt-system.mjs" ]]; then
  echo "--> Building prompt system..."
  BUILD_FLAGS=""
  $DEBUG_MODE && BUILD_FLAGS="$BUILD_FLAGS --debug"
  $SCAFFOLDED_MODE && BUILD_FLAGS="$BUILD_FLAGS --scaffolded"
  node "$REPO_DIR/scripts/build-prompt-system.mjs" $BUILD_FLAGS
  echo ""
fi

if [[ ! -d "$SRC_CLAUDE" ]]; then
  echo "ERROR: Generated files not found and no build script available."
  exit 1
fi

# --- Auto-detect if no targets specified ---

if [[ ${#TARGETS[@]} -eq 0 ]]; then
  read -ra TARGETS <<< "$(detect_editors)"
fi

if [[ ${#TARGETS[@]} -eq 0 ]]; then
  echo "ERROR: No supported editors detected. Use --claude, --cursor, --windsurf, --codex, or --opencode."
  exit 1
fi

# --- List path ---

if [[ "$DO_LIST" == true ]]; then
  echo "==> agent-historic installed files"
  echo "    Targets: ${TARGETS[*]}"
  echo ""
  for target in "${TARGETS[@]}"; do
    "list_${target}"
    echo ""
  done
  echo "==> No files were modified."
  exit 0
fi

# --- Install path ---

echo "==> agent-historic persona install"
echo "    Source:  $REPO_DIR"
echo "    Targets: ${TARGETS[*]}"
echo "    Style:   rich (universal default)"
echo ""

echo "--> Backing up existing rule directories..."
for target in "${TARGETS[@]}"; do
  case "$target" in
    claude)   backup_dir "$DEST_CLAUDE" ;;
    cursor)   backup_dir "$DEST_CURSOR" ;;
    windsurf) backup_dir "$DEST_WINDSURF" ;;
    codex)    backup_dir "$DEST_CODEX" ;;
    opencode) backup_dir "$DEST_OPENCODE" ;;
  esac
done

echo "--> Installing rules..."
for target in "${TARGETS[@]}"; do
  "install_${target}"
done

echo ""
echo "==> Done."

print_post_install "${TARGETS[@]}"
