#!/usr/bin/env node
/**
 * Unified install script for Agent Historic persona rules.
 *
 * Cross-platform Node.js implementation. Replaces install-local.sh and
 * install-local.ps1 with a single canonical entry point.
 *
 * Usage:
 *   node install.js [options]
 *
 * Options:
 *   --claude       Install rules for Claude Code
 *   --cursor       Install rules for Cursor
 *   --windsurf     Install rules for Windsurf
 *   --codex        Install rules for Codex
 *   --crush        Install rules for Crush
 *   --opencode     Install rules for OpenCode
 *   --gemini       Install rules for Gemini CLI
 *   --all          Install for all editors
 *   --list         List installed files and their status (no changes made)
 *   --scaffolded   Build with scaffolded voice (passed through to build script)
 *   --debug        Build with debug routing preamble (passed through to build script)
 *   -h, --help     Show this help
 *
 * If no flags are provided, the script auto-detects installed editors.
 */

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const repoDir = path.dirname(path.resolve(__filename));

// --- Constants -------------------------------------------------------------

const MANAGED_MARKER = 'managed_by: agent-historic';
const MARKER_BEGIN = '<!-- agent-historic:loader-begin -->';
const MARKER_END = '<!-- agent-historic:loader-end -->';

const HOME = os.homedir();
const APPDATA = process.env.APPDATA;

// --- Source dirs (generated by scripts/build-prompt-system.mjs) -----------

const SRC = {
  claude: path.join(repoDir, 'compiled', 'claude', 'rules'),
  cursor: path.join(repoDir, 'compiled', 'cursor', 'rules'),
  windsurf: path.join(repoDir, 'compiled', 'windsurf', 'rules'),
  codex: path.join(repoDir, 'compiled', 'codex'),
  crush: path.join(repoDir, 'compiled', 'crush', 'rules'),
  gemini: path.join(repoDir, 'compiled', 'gemini', 'rules'),
};
SRC.opencode = SRC.claude; // OpenCode shares Claude's rich source

// --- Destination dirs ------------------------------------------------------

const DEST = {
  claude: path.join(HOME, '.claude', 'rules'),
  claudeMd: path.join(HOME, '.claude', 'CLAUDE.md'),
  cursor: path.join(HOME, '.cursor', 'rules'),
  windsurf: path.join(HOME, '.windsurf', 'rules'),
  windsurfMd: path.join(HOME, '.windsurf', 'WINDSURF.md'),
  windsurfMemories: path.join(HOME, '.codeium', 'windsurf', 'memories'),
  codex: path.join(HOME, '.codex'),
  crush: APPDATA
    ? path.join(APPDATA, 'crush', 'rules')
    : path.join(HOME, '.config', 'crush', 'rules'),
  crushMd: APPDATA
    ? path.join(APPDATA, 'crush', 'CRUSH.md')
    : path.join(HOME, '.config', 'crush', 'CRUSH.md'),
  crushJson: APPDATA
    ? path.join(APPDATA, 'crush', 'crush.json')
    : path.join(HOME, '.config', 'crush', 'crush.json'),
  opencode: APPDATA
    ? path.join(APPDATA, 'opencode', 'rules')
    : path.join(HOME, '.config', 'opencode', 'rules'),
  opencodeJson: APPDATA
    ? path.join(APPDATA, 'opencode', 'opencode.json')
    : path.join(HOME, '.config', 'opencode', 'opencode.json'),
  opencodeAgents: APPDATA
    ? path.join(APPDATA, 'opencode', 'AGENTS.md')
    : path.join(HOME, '.config', 'opencode', 'AGENTS.md'),
  gemini: path.join(HOME, '.gemini', 'rules'),
  geminiMd: path.join(HOME, '.gemini', 'GEMINI.md'),
};

// --- Filesystem helpers ----------------------------------------------------

function ensureDir(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function listFilesByExt(dir, ext) {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((name) => name.endsWith(ext))
    .map((name) => path.join(dir, name));
}

function readText(file) {
  return fs.readFileSync(file, 'utf8');
}

function writeText(file, content) {
  ensureDir(path.dirname(file));
  fs.writeFileSync(file, content);
}

function fileExists(file) {
  try {
    return fs.statSync(file).isFile();
  } catch {
    return false;
  }
}

function dirExists(dir) {
  try {
    return fs.statSync(dir).isDirectory();
  } catch {
    return false;
  }
}

function fileContains(file, marker) {
  if (!fileExists(file)) return false;
  return readText(file).includes(marker);
}

function cleanupManagedFiles(destDir) {
  if (!dirExists(destDir)) return;
  const walk = (d) => {
    for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
      const full = path.join(d, entry.name);
      if (entry.isDirectory()) {
        walk(full);
      } else if (entry.isFile() && fileContains(full, MANAGED_MARKER)) {
        fs.unlinkSync(full);
        console.log(`    Removed stale: ${full}`);
      }
    }
  };
  walk(destDir);
}

function copyFilesByExt(srcDir, ext, destDir, label) {
  ensureDir(destDir);
  cleanupManagedFiles(destDir);
  for (const src of listFilesByExt(srcDir, ext)) {
    const target = path.join(destDir, path.basename(src));
    fs.copyFileSync(src, target);
    console.log(`    ${(label + ':').padEnd(9)} ${target}`);
  }
}

function copyDirRecursive(srcDir, destDir) {
  ensureDir(destDir);
  for (const entry of fs.readdirSync(srcDir, { withFileTypes: true })) {
    const src = path.join(srcDir, entry.name);
    const dst = path.join(destDir, entry.name);
    if (entry.isDirectory()) {
      copyDirRecursive(src, dst);
    } else if (entry.isFile()) {
      fs.copyFileSync(src, dst);
    }
  }
}

function timestampSuffix() {
  const d = new Date();
  const pad = (n) => String(n).padStart(2, '0');
  return (
    d.getFullYear().toString() +
    pad(d.getMonth() + 1) +
    pad(d.getDate()) +
    pad(d.getHours()) +
    pad(d.getMinutes()) +
    pad(d.getSeconds())
  );
}

// --- Loader-header injection -----------------------------------------------

function buildLoaderBlock(rulesDir, title) {
  return (
    `${MARKER_BEGIN}\n` +
    `# ${title}\n\n` +
    `At the start of every conversation, preload these rule files (they define mandatory protocols):\n` +
    `1. \`${rulesDir}/00-init.md\` -- Global Operating System. Always active. Defines universal mandates that supersede individual expert personas. Don't skip this.\n` +
    `2. \`${rulesDir}/01-router.md\` -- MoE Router. Front-line triage. Analyzes intent and routes to the correct expert or pipeline.\n\n` +
    `These files establish the core protocol: routing before acting, logging all command output, labeling uncertainty (VERIFIED/HYPOTHESIS), and following the definition of done.\n` +
    `${MARKER_END}`
  );
}

function injectLoaderHeader(file, rulesDir, title) {
  const block = buildLoaderBlock(rulesDir, title);
  let content = '';
  if (fileExists(file)) {
    content = readText(file);
  } else {
    ensureDir(path.dirname(file));
  }

  let updated;
  if (content.includes(MARKER_BEGIN) && content.includes(MARKER_END)) {
    const start = content.indexOf(MARKER_BEGIN);
    let finish = content.indexOf(MARKER_END, start);
    finish += MARKER_END.length;
    if (finish < content.length && content[finish] === '\n') finish += 1;
    updated = content.slice(0, start) + block + '\n' + content.slice(finish);
  } else if (!content.trim()) {
    updated = block + '\n';
  } else {
    updated = block + '\n\n' + content;
  }
  fs.writeFileSync(file, updated);
  console.log(`    Loader:   ${file}`);
}

function replaceLoaderBlock(file, newBlock, label) {
  let content = '';
  if (fileExists(file)) {
    content = readText(file);
  } else {
    ensureDir(path.dirname(file));
  }
  let updated;
  if (content.includes(MARKER_BEGIN) && content.includes(MARKER_END)) {
    const start = content.indexOf(MARKER_BEGIN);
    let finish = content.indexOf(MARKER_END, start);
    finish += MARKER_END.length;
    if (finish < content.length && content[finish] === '\n') finish += 1;
    updated = content.slice(0, start) + newBlock + '\n' + content.slice(finish);
  } else if (!content.trim()) {
    updated = newBlock + '\n';
  } else {
    updated = newBlock + '\n\n' + content;
  }
  fs.writeFileSync(file, updated);
  console.log(`    ${label}: ${file}`);
}

// --- Tool-specific custom loader blocks ------------------------------------

const OPENCODE_BOOT_PROMPT =
  '<!-- agent-historic:loader-begin -->\n' +
  '# CRITICAL: MANDATORY BOOT PROTOCOL\n' +
  'Before generating ANY response or answering ANY user inquiry in the first turn, you MUST execute the following sequence:\n\n' +
  '1. **Preload & Audit:** In parallel, call `read` for `~/.config/opencode/rules/00-init.md` and `~/.config/opencode/rules/01-router.md`, and `glob` for `~/.config/opencode/rules/*` to verify the expert roster against the filesystem.\n' +
  '2. **Initialize Logging:** Execute `mkdir -p .logs` via `bash` to ensure the Non-Destructive Logging Protocol is viable immediately.\n' +
  '3. **Verification:** Confirm the `[rules:loaded...]` token is present and expert files match the expected roster.\n' +
  '4. **Response Barrier:** Do not provide any conversational output until all tools above have returned and verification is complete.\n\n' +
  'Failure to perform this sequence is a violation of the System Integrity mandate.\n\n' +
  '<!-- agent-historic:loader-end -->';

const OPENCODE_DEFAULT_JSON = {
  $schema: 'https://opencode.ai/config.json',
  agent: {
    build: {
      prompt: OPENCODE_BOOT_PROMPT,
    },
  },
  permission: {
    external_directory: {
      '**/.config/opencode/**': 'allow',
    },
  },
};

function buildGeminiBootBlock() {
  return (
    `${MARKER_BEGIN}\n` +
    '# CRITICAL: MANDATORY BOOT PROTOCOL\n' +
    'Before generating ANY response or answering ANY user inquiry in the first turn, you MUST execute the following sequence:\n\n' +
    '1. **Preload & Audit:** In parallel, call `read_file` for `~/.gemini/rules/00-init.md` and `~/.gemini/rules/01-router.md`, and `list_directory` for `~/.gemini/rules/` to verify the expert roster against the filesystem.\n' +
    '2. **Initialize Logging:** Execute `mkdir -p .logs` via `run_shell_command` to ensure the Non-Destructive Logging Protocol is viable immediately.\n' +
    '3. **Verification:** Confirm the `[rules:loaded...]` token is present and expert files match the expected roster.\n' +
    '4. **Response Barrier:** Do not provide any conversational output until all tools above have returned and verification is complete.\n\n' +
    'Failure to perform this sequence is a violation of the System Integrity mandate.\n\n' +
    `${MARKER_END}`
  );
}

// --- Install functions per editor -----------------------------------------

function installClaude() {
  copyFilesByExt(SRC.claude, '.md', DEST.claude, 'Claude');
  injectLoaderHeader(DEST.claudeMd, '~/.claude/rules', 'Claude Code Instructions');
}

function installCursor() {
  copyFilesByExt(SRC.cursor, '.mdc', DEST.cursor, 'Cursor');
}

function installWindsurf() {
  copyFilesByExt(SRC.windsurf, '.md', DEST.windsurf, 'Windsurf');
  injectLoaderHeader(DEST.windsurfMd, '~/.windsurf/rules', 'Windsurf Instructions');

  // Export global_rules.md to Windsurf memories for preload on every chat.
  ensureDir(DEST.windsurfMemories);
  const wsGlobal = path.join(DEST.windsurfMemories, 'global_rules.md');
  const wsContent =
    '# Load These First\n' +
    'At the start of every conversation, preload these rule files (they define mandatory protocols):\n' +
    `1. \`${path.join(HOME, '.windsurf/rules/00-init.md')}\` -- Global Operating System. Always active. Defines universal mandates that supersede individual expert personas. Don't skip this.\n` +
    `2. \`${path.join(HOME, '.windsurf/rules/01-router.md')}\` -- MoE Router. Front-line triage. Analyzes intent and routes to the correct expert or pipeline.\n` +
    'These files establish the core protocol: routing before acting, logging all command output, labeling uncertainty (VERIFIED/HYPOTHESIS), and following the definition of done.\n';
  fs.writeFileSync(wsGlobal, wsContent);
  console.log(`    Memories: ${wsGlobal}`);
}

function installCodex() {
  ensureDir(DEST.codex);
  cleanupManagedFiles(DEST.codex);
  copyDirRecursive(SRC.codex, DEST.codex);
  console.log(`    Codex:    ${DEST.codex}/`);
}

function installCrush() {
  copyFilesByExt(SRC.crush, '.md', DEST.crush, 'Crush');
  injectLoaderHeader(DEST.crushMd, '~/.config/crush/rules', 'Crush Instructions');

  // Ensure crush.json has context_paths pointing to the rules and CRUSH.md.
  const ctxCrush = '~/.config/crush/CRUSH.md';
  const ctxRules = '~/.config/crush/rules/';
  const existed = fileExists(DEST.crushJson);
  let cfg = {};
  if (existed) {
    try {
      cfg = JSON.parse(readText(DEST.crushJson));
    } catch (err) {
      console.log(`    Warning: ${DEST.crushJson} is invalid JSON; rewriting. (${err.message})`);
      cfg = {};
    }
  }
  cfg.options = cfg.options || {};
  cfg.options.context_paths = Array.isArray(cfg.options.context_paths)
    ? cfg.options.context_paths
    : [];
  let changed = false;
  for (const p of [ctxCrush, ctxRules]) {
    if (!cfg.options.context_paths.includes(p)) {
      cfg.options.context_paths.push(p);
      changed = true;
    }
  }
  if (changed || !existed) {
    writeText(DEST.crushJson, JSON.stringify(cfg, null, 2) + '\n');
    const verb = existed ? 'updated' : 'created';
    console.log(`    Config:   ${DEST.crushJson} (${verb} context_paths)`);
  }
}

function installOpenCode() {
  copyFilesByExt(SRC.opencode, '.md', DEST.opencode, 'OpenCode');

  // opencode.json: preserve existing files (with timestamped backup); only
  // create a fresh one when the file is absent. Manual merge is left to the
  // user when an existing config is detected.
  if (fileExists(DEST.opencodeJson)) {
    const backup = `${DEST.opencodeJson}.bak.${timestampSuffix()}`;
    fs.copyFileSync(DEST.opencodeJson, backup);
    console.log(`    Backup:   ${backup}`);
    console.log(`    Note: opencode.json exists. Manual merge may be needed for the prompt field.`);
  } else {
    writeText(DEST.opencodeJson, JSON.stringify(OPENCODE_DEFAULT_JSON, null, 2) + '\n');
  }
  console.log(`    Config:   ${DEST.opencodeJson}`);

  // AGENTS.md: idempotent loader-header injection.
  injectLoaderHeader(DEST.opencodeAgents, '~/.config/opencode/rules', 'Agent Instructions');
}

function installGemini() {
  copyFilesByExt(SRC.gemini, '.md', DEST.gemini, 'Gemini');
  // Replace (or write) GEMINI.md with the tool-specific boot block.
  if (fileExists(DEST.geminiMd)) {
    const backup = `${DEST.geminiMd}.bak.${timestampSuffix()}`;
    fs.copyFileSync(DEST.geminiMd, backup);
    console.log(`    Backup:   ${backup}`);
  }
  replaceLoaderBlock(DEST.geminiMd, buildGeminiBootBlock(), 'Loader  ');
}

// --- List functions per editor --------------------------------------------

function statusLabel(file) {
  return fileExists(file) ? 'installed' : 'not found';
}

function listSimple(label, srcDir, ext, destDir, extras = []) {
  console.log(`    ${label}:`);
  for (const src of listFilesByExt(srcDir, ext)) {
    const target = path.join(destDir, path.basename(src));
    console.log(`      ${target}  [${statusLabel(target)}]`);
  }
  for (const extra of extras) {
    console.log(`      ${extra}  [${statusLabel(extra)}]`);
  }
}

const LISTERS = {
  claude: () => listSimple('Claude (~/.claude/rules/)', SRC.claude, '.md', DEST.claude, [DEST.claudeMd]),
  cursor: () => listSimple('Cursor (~/.cursor/rules/)', SRC.cursor, '.mdc', DEST.cursor),
  windsurf: () => listSimple('Windsurf (~/.windsurf/rules/)', SRC.windsurf, '.md', DEST.windsurf, [DEST.windsurfMd]),
  codex: () => {
    console.log('    Codex (~/.codex/):');
    const target = path.join(DEST.codex, 'AGENTS.md');
    console.log(`      ${target}  [${statusLabel(target)}]`);
  },
  crush: () => listSimple('Crush', SRC.crush, '.md', DEST.crush, [DEST.crushMd]),
  opencode: () => listSimple('OpenCode', SRC.opencode, '.md', DEST.opencode, [DEST.opencodeAgents]),
  gemini: () => listSimple('Gemini (~/.gemini/rules/)', SRC.gemini, '.md', DEST.gemini, [DEST.geminiMd]),
};

const INSTALLERS = {
  claude: installClaude,
  cursor: installCursor,
  windsurf: installWindsurf,
  codex: installCodex,
  crush: installCrush,
  opencode: installOpenCode,
  gemini: installGemini,
};

// --- Auto-detection --------------------------------------------------------

function detectEditors() {
  const detected = [];
  if (dirExists(path.join(HOME, '.claude'))) detected.push('claude');
  if (dirExists(path.join(HOME, '.cursor'))) detected.push('cursor');
  if (
    dirExists(path.join(HOME, '.windsurf')) ||
    dirExists(path.join(HOME, '.codeium', 'windsurf'))
  ) {
    detected.push('windsurf');
  }
  if (dirExists(path.join(HOME, '.codex'))) detected.push('codex');
  if (
    (APPDATA && dirExists(path.join(APPDATA, 'crush'))) ||
    dirExists(path.join(HOME, '.config', 'crush'))
  ) {
    detected.push('crush');
  }
  if (
    (APPDATA && dirExists(path.join(APPDATA, 'opencode'))) ||
    dirExists(path.join(HOME, '.config', 'opencode'))
  ) {
    detected.push('opencode');
  }
  if (dirExists(path.join(HOME, '.gemini'))) detected.push('gemini');
  return detected;
}

// --- CLI parsing -----------------------------------------------------------

function printHelp() {
  process.stdout.write(`Usage: node install.js [options]

Options:
  --claude       Install rules for Claude Code
  --cursor       Install rules for Cursor
  --windsurf     Install rules for Windsurf
  --codex        Install rules for Codex
  --crush        Install rules for Crush
  --opencode     Install rules for OpenCode
  --gemini       Install rules for Gemini CLI
  --all          Install for all editors
  --list         List installed files and their status (no changes made)
  --scaffolded   Build with scaffolded voice (externalized reasoning labels)
  --debug        Build with debug routing preamble visible
  -h, --help     Show this help

No flags = auto-detect installed editors.

Before running (if compiled output is missing), the script invokes:
  node scripts/build-prompt-system.mjs
`);
}

function parseArgs(argv) {
  const targets = [];
  const flags = { list: false, debug: false, scaffolded: false, help: false };
  for (const arg of argv) {
    switch (arg) {
      case '--claude': targets.push('claude'); break;
      case '--cursor': targets.push('cursor'); break;
      case '--windsurf': targets.push('windsurf'); break;
      case '--codex': targets.push('codex'); break;
      case '--crush': targets.push('crush'); break;
      case '--opencode': targets.push('opencode'); break;
      case '--gemini': targets.push('gemini'); break;
      case '--all':
        targets.push('claude', 'cursor', 'windsurf', 'codex', 'crush', 'opencode', 'gemini');
        break;
      case '--list': flags.list = true; break;
      case '--debug': flags.debug = true; break;
      case '--scaffolded': flags.scaffolded = true; break;
      case '-h':
      case '--help': flags.help = true; break;
      default:
        console.error(`Unknown option: ${arg}`);
        console.error('Run: node install.js --help');
        process.exit(1);
    }
  }
  return { targets, flags };
}

// --- Build orchestration ---------------------------------------------------

function maybeBuildPromptSystem(flags) {
  const buildScript = path.join(repoDir, 'scripts', 'build-prompt-system.mjs');
  const compiledReady =
    dirExists(SRC.claude) && listFilesByExt(SRC.claude, '.md').length > 0;

  const customFlags = flags.debug || flags.scaffolded;

  if (customFlags && fileExists(buildScript)) {
    console.log('--> Rebuilding prompt system (custom flags)...');
    const args = [buildScript];
    if (flags.debug) args.push('--debug');
    if (flags.scaffolded) args.push('--scaffolded');
    runNode(args);
  } else if (compiledReady) {
    console.log('--> Compiled files found, skipping build.');
  } else if (fileExists(buildScript)) {
    console.log('--> Building prompt system...');
    runNode([buildScript, '--no-debug']);
  } else {
    console.error('ERROR: Generated files not found and no build script available.');
    process.exit(1);
  }
  console.log('');
}

function runNode(args) {
  const result = spawnSync(process.execPath, args, {
    stdio: 'inherit',
    cwd: repoDir,
  });
  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

// --- Post-install notes ----------------------------------------------------

function printPostInstall(targets, flags) {
  console.log('');
  console.log('=== POST-INSTALL: REQUIRED IDE CONFIGURATION ===');
  console.log('');
  console.log(`  Voice: ${flags.scaffolded ? 'scaffolded (externalized reasoning with explicit labels).' : 'calibrated (internalized, peer-like prose).'}`);
  console.log('  Rich rules are installed as the universal default for all models.');
  console.log('');

  const notes = {
    claude: [
      '  Claude Code',
      '    Rules installed to ~/.claude/rules/.',
      '    CLAUDE.md loader header injected into ~/.claude/CLAUDE.md.',
      '    No extra config needed.',
    ],
    cursor: [
      '  Cursor (IMPORTANT)',
      '    1. Open Cursor Settings > Rules for AI',
      '    2. 00-init must load on every request (alwaysApply: true).',
      '    3. 01-router must load on every request (alwaysApply: true).',
      '    4. Expert rules (expert-*.mdc) are auto-attached by Cursor',
      '       when their description matches the conversation context.',
      '    Files: ~/.cursor/rules/',
    ],
    windsurf: [
      '  Windsurf (IMPORTANT)',
      '    1. Open Windsurf > Customizations > Rules',
      '    2. 00-init.md has trigger: always - global runtime.',
      '    3. 01-router.md has trigger: always - request triage.',
      '    4. Expert rules use trigger: model_decision - Cascade reads',
      '       them automatically when the description matches.',
      '    Files: ~/.windsurf/rules/',
    ],
    codex: [
      '  Codex',
      '    AGENTS.md and skills/ are installed to ~/.codex/.',
      '    No extra config needed.',
    ],
    crush: [
      '  Crush',
      '    Rules installed to ~/.config/crush/rules/ (or %APPDATA%\\crush\\rules\\ on Windows).',
      '    CRUSH.md loader header injected.',
      '    context_paths added to crush.json.',
    ],
    opencode: [
      '  OpenCode',
      '    Rules installed to ~/.config/opencode/rules/ (or %APPDATA%\\opencode\\rules\\ on Windows).',
      '    AGENTS.md loader header injected.',
      '    opencode.json: existing config preserved with timestamped backup.',
    ],
    gemini: [
      '  Gemini CLI',
      '    Rules installed to ~/.gemini/rules/.',
      '    GEMINI.md boot-protocol block injected.',
      '    Gemini CLI loads rules via native @file.md import syntax.',
    ],
  };

  for (const t of targets) {
    if (notes[t]) {
      for (const line of notes[t]) console.log(line);
      console.log('');
    }
  }

  console.log("  Tip: Run 'node install.js --list' to verify installed files.");
  console.log('');
}

// --- Main ------------------------------------------------------------------

function main(argv) {
  const { targets, flags } = parseArgs(argv);

  if (flags.help) {
    printHelp();
    return;
  }

  // Build (or skip) before any install/list work.
  maybeBuildPromptSystem(flags);

  let resolvedTargets = targets.length ? Array.from(new Set(targets)) : detectEditors();

  if (resolvedTargets.length === 0) {
    console.error(
      'ERROR: No supported editors detected. Use --claude, --cursor, --windsurf, --codex, --crush, --opencode, or --gemini.'
    );
    process.exit(1);
  }

  if (flags.list) {
    console.log('==> agent-historic installed files');
    console.log(`    Targets: ${resolvedTargets.join(' ')}`);
    console.log('');
    for (const t of resolvedTargets) {
      LISTERS[t]();
      console.log('');
    }
    console.log('==> No files were modified.');
    return;
  }

  console.log('==> agent-historic persona install');
  console.log(`    Source:  ${repoDir}`);
  console.log(`    Targets: ${resolvedTargets.join(' ')}`);
  console.log('    Style:   rich (universal default)');
  console.log('');
  console.log('--> Installing rules...');
  for (const t of resolvedTargets) {
    INSTALLERS[t]();
  }
  console.log('');
  console.log('==> Done.');

  printPostInstall(resolvedTargets, flags);
}

main(process.argv.slice(2));
