#!/usr/bin/env pwsh
# install-local.ps1 -- Install Agent Historic persona rules into AI coding editors on Windows/PowerShell.
# Usage: powershell -ExecutionPolicy Bypass -File .\install-local.ps1 [--claude] [--cursor] [--windsurf] [--codex] [--opencode] [--gemini] [--all]
# No flags = auto-detect installed editors.

param(
  [switch]$claude,
  [switch]$cursor,
  [switch]$windsurf,
  [switch]$codex,
  [switch]$crush,
  [switch]$opencode,
  [switch]$gemini,
  [switch]$all,
  [switch]$list,
  [switch]$debug,
  [switch]$scaffolded,
  [switch]$help
)

$ErrorActionPreference = "Stop"

if ($help) {
  Write-Host "Usage: powershell -ExecutionPolicy Bypass -File .\install-local.ps1 [options]"
  Write-Host ""
  Write-Host "Options:"
  Write-Host "  --claude       Install rules for Claude Code"
  Write-Host "  --cursor       Install rules for Cursor"
  Write-Host "  --windsurf     Install rules for Windsurf"
  Write-Host "  --codex        Install rules for Codex"
  Write-Host "  --crush        Install rules for Crush"
  Write-Host "  --opencode     Install rules for OpenCode"
  Write-Host "  --gemini       Install rules for Gemini CLI"
  Write-Host "  --all          Install for all editors"
  Write-Host "  --list         List installed files and their status (no changes made)"
  Write-Host "  --scaffolded   Use scaffolded voice during build"
  Write-Host "  --debug        Include debug routing preamble during build"
  Write-Host "  --help         Show this help"
  Write-Host ""
  Write-Host "No flags = auto-detect installed editors."
  exit 0
}

$repoDir = Split-Path -Parent $MyInvocation.MyCommand.Path

# Source directories (generated by scripts/build-prompt-system.mjs)
$srcClaude = Join-Path $repoDir "compiled/claude/rules"
$srcCursor = Join-Path $repoDir "compiled/cursor/rules"
$srcWindsurf = Join-Path $repoDir "compiled/windsurf/rules"
$srcCodex = Join-Path $repoDir "compiled/codex"
$srcCrush = Join-Path $repoDir "compiled/crush/rules"
$srcOpenCode = $srcClaude
$srcGemini = Join-Path $repoDir "compiled/gemini/rules"

# Target directories (Windows defaults)
$homeDir = $HOME
$appData = $env:APPDATA
$destClaude = Join-Path $homeDir ".claude/rules"
$destCursor = Join-Path $homeDir ".cursor/rules"
$destWindsurf = Join-Path $homeDir ".windsurf/rules"
$destCodex = Join-Path $homeDir ".codex"
$destCrush = if ($appData) { Join-Path $appData "crush/rules" } else { Join-Path $homeDir ".config/crush/rules" }
$crushMd = if ($appData) { Join-Path $appData "crush/CRUSH.md" } else { Join-Path $homeDir ".config/crush/CRUSH.md" }
$crushJson = if ($appData) { Join-Path $appData "crush/crush.json" } else { Join-Path $homeDir ".config/crush/crush.json" }
$destOpenCode = if ($appData) { Join-Path $appData "opencode/rules" } else { Join-Path $homeDir ".config/opencode/rules" }
$openCodeAgents = if ($appData) { Join-Path $appData "opencode/AGENTS.md" } else { Join-Path $homeDir ".config/opencode/AGENTS.md" }
$destGemini = Join-Path $homeDir ".gemini/rules"
$geminiMd = Join-Path $homeDir ".gemini/GEMINI.md"

$managedMarker = "managed_by: agent-historic"
$markerBegin = "<!-- agent-historic:loader-begin -->"
$markerEnd = "<!-- agent-historic:loader-end -->"

function Ensure-Dir([string]$path) {
  if (-not (Test-Path $path)) {
    New-Item -ItemType Directory -Path $path -Force | Out-Null
  }
}

function Cleanup-ManagedFiles([string]$destDir) {
  if (-not (Test-Path $destDir)) { return }
  Get-ChildItem -Path $destDir -Recurse -File -ErrorAction SilentlyContinue | ForEach-Object {
    $f = $_.FullName
    if (Select-String -Path $f -Pattern ([Regex]::Escape($managedMarker)) -Quiet -ErrorAction SilentlyContinue) {
      Remove-Item -Path $f -Force
      Write-Host "    Removed stale: $f"
    }
  }
}

function Inject-LoaderHeader([string]$file, [string]$rulesDir, [string]$title) {
  $block = @"
$markerBegin
# $title

At the start of every conversation, preload these rule files (they define mandatory protocols):
1. `$rulesDir/00-init.md` -- Global Operating System. Always active. Defines universal mandates that supersede individual expert personas. Don't skip this.
2. `$rulesDir/01-router.md` -- MoE Router. Front-line triage. Analyzes intent and routes to the correct expert or pipeline.

These files establish the core protocol: routing before acting, logging all command output, labeling uncertainty (VERIFIED/HYPOTHESIS), and following the definition of done.
$markerEnd
"@

  $content = ""
  if (Test-Path $file) {
    $content = Get-Content -Path $file -Raw
  } else {
    Ensure-Dir (Split-Path -Parent $file)
  }

  if ($content.Contains($markerBegin) -and $content.Contains($markerEnd)) {
    $start = $content.IndexOf($markerBegin)
    $finish = $content.IndexOf($markerEnd, $start)
    if ($start -ge 0 -and $finish -ge 0) {
      $finish = $finish + $markerEnd.Length
      if ($finish -lt $content.Length -and $content[$finish] -eq "`n") {
        $finish += 1
      }
      $updated = $content.Substring(0, $start) + $block + "`n" + $content.Substring($finish)
      Set-Content -Path $file -Value $updated -NoNewline
    }
  } elseif ([string]::IsNullOrWhiteSpace($content)) {
    Set-Content -Path $file -Value $block -NoNewline
  } else {
    Set-Content -Path $file -Value ($block + "`n`n" + $content) -NoNewline
  }

  Write-Host "    Loader:   $file"
}

function Copy-GlobToDest([string]$pattern, [string]$dest, [string]$label) {
  Ensure-Dir $dest
  Cleanup-ManagedFiles $dest
  $files = Get-ChildItem -Path $pattern -File -ErrorAction SilentlyContinue
  foreach ($f in $files) {
    Copy-Item -Path $f.FullName -Destination (Join-Path $dest $f.Name) -Force
    Write-Host ("    {0,-9} {1}" -f ($label + ":"), (Join-Path $dest $f.Name))
  }
}

function Install-Claude {
  Copy-GlobToDest (Join-Path $srcClaude "*.md") $destClaude "Claude"
  Inject-LoaderHeader (Join-Path $homeDir ".claude/CLAUDE.md") "~/.claude/rules" "Claude Code Instructions"
}

function Install-Cursor {
  Copy-GlobToDest (Join-Path $srcCursor "*.mdc") $destCursor "Cursor"
}

function Install-Windsurf {
  Copy-GlobToDest (Join-Path $srcWindsurf "*.md") $destWindsurf "Windsurf"
  Inject-LoaderHeader (Join-Path $homeDir ".windsurf/WINDSURF.md") "~/.windsurf/rules" "Windsurf Instructions"
  # Export global_rules.md to Windsurf memories for preload on every chat
  $wsMemories = Join-Path $homeDir ".codeium/windsurf/memories"
  Ensure-Dir $wsMemories
  $wsGlobal = Join-Path $wsMemories "global_rules.md"
  $wsGlobalContent = @"
# Load These First
At the start of every conversation, preload these rule files (they define mandatory protocols):
1. \`~/.windsurf/rules/00-init.md\` -- Global Operating System. Always active. Defines universal mandates that supersede individual expert personas. Don't skip this.
2. \`~/.windsurf/rules/01-router.md\` -- MoE Router. Front-line triage. Analyzes intent and routes to the correct expert or pipeline.
These files establish the core protocol: routing before acting, logging all command output, labeling uncertainty (VERIFIED/HYPOTHESIS), and following the definition of done.
"@
  Set-Content -Path $wsGlobal -Value $wsGlobalContent -NoNewline
  Write-Host "    Memories: $wsGlobal"
}

function Install-Codex {
  Ensure-Dir $destCodex
  Cleanup-ManagedFiles $destCodex
  Copy-Item -Path (Join-Path $srcCodex "*") -Destination $destCodex -Recurse -Force
  Write-Host "    Codex:    $destCodex"
}

function Install-Crush {
  Copy-GlobToDest (Join-Path $srcCrush "*.md") $destCrush "Crush"
  Inject-LoaderHeader $crushMd "~/.config/crush/rules" "Crush Instructions"
  # Ensure crush.json has context_paths
  $ctxCrush = "~/.config/crush/CRUSH.md"
  $ctxRules = "~/.config/crush/rules/"
  if (Test-Path $crushJson) {
    $cfg = Get-Content -Path $crushJson -Raw | ConvertFrom-Json
    if (-not $cfg.options) { $cfg | Add-Member -NotePropertyName options -NotePropertyValue ([PSCustomObject]@{}) }
    if (-not $cfg.options.context_paths) { $cfg.options | Add-Member -NotePropertyName context_paths -NotePropertyValue @() }
    $paths = [System.Collections.ArrayList]@($cfg.options.context_paths)
    $changed = $false
    if ($ctxCrush -notin $paths) { [void]$paths.Add($ctxCrush); $changed = $true }
    if ($ctxRules -notin $paths) { [void]$paths.Add($ctxRules); $changed = $true }
    if ($changed) {
      $cfg.options.context_paths = $paths.ToArray()
      $cfg | ConvertTo-Json -Depth 10 | Set-Content -Path $crushJson
      Write-Host "    Config:   $crushJson (added context_paths)"
    }
  } else {
    Ensure-Dir (Split-Path -Parent $crushJson)
    @{ options = @{ context_paths = @($ctxCrush, $ctxRules) } } | ConvertTo-Json -Depth 10 | Set-Content -Path $crushJson
    Write-Host "    Config:   $crushJson (created with context_paths)"
  }
}

function Install-OpenCode {
  Copy-GlobToDest (Join-Path $srcOpenCode "*.md") $destOpenCode "OpenCode"
  # Write custom opencode.json with tool-specific loader protocol (non-destructive: only if file exists)
  $opencodeJson = Join-Path $homeDir ".config/opencode/opencode.json"
  if (Test-Path $opencodeJson) {
    # Backup existing file
    $backup = "$opencodeJson.bak.$(Get-Date -Format 'yyyyMMddHHmmss')"
    Copy-Item -Path $opencodeJson -Destination $backup -Force
    Write-Host "    Backup:   $backup"
    # Inject prompt into existing JSON (simplified - just note that manual merge may be needed)
    Write-Host "    Note: opencode.json exists. Manual merge may be needed for the prompt field."
  } else {
    Ensure-Dir (Split-Path -Parent $opencodeJson)
    $opencodeContent = @"
{
  "`$schema": "https://opencode.ai/config.json",
  "agent": {
    "build": {
      "prompt": "<!-- agent-historic:loader-begin -->\n# CRITICAL: MANDATORY BOOT PROTOCOL\nBefore generating ANY response or answering ANY user inquiry in the first turn, you MUST execute the following sequence:\n\n1. **Preload & Audit:** In parallel, call `read` for `~/.config/opencode/rules/00-init.md` and `~/.config/opencode/rules/01-router.md`, and `glob` for `~/.config/opencode/rules/*` to verify the expert roster against the filesystem.\n2. **Initialize Logging:** Execute `mkdir -p .logs` via `bash` to ensure the Non-Destructive Logging Protocol is viable immediately.\n3. **Verification:** Confirm the `[rules:loaded...]` token is present and expert files match the expected roster.\n4. **Response Barrier:** Do not provide any conversational output until all tools above have returned and verification is complete.\n\nFailure to perform this sequence is a violation of the System Integrity mandate.\n\n<!-- agent-historic:loader-end -->"
    }
  },
  "permission": {
    "external_directory": {
      "**/.config/opencode/**": "allow"
    }
  }
}
"@
    Set-Content -Path $opencodeJson -Value $opencodeContent -NoNewline
  }
  Write-Host "    Config:   $opencodeJson"
  # Inject loader header into AGENTS.md if it exists, otherwise create it
  $agentsFile = Join-Path $homeDir ".config/opencode/AGENTS.md"
  if (Test-Path $agentsFile) {
    # Backup existing file
    $backup = "$agentsFile.bak.$(Get-Date -Format 'yyyyMMddHHmmss')"
    Copy-Item -Path $agentsFile -Destination $backup -Force
    Write-Host "    Backup:   $backup"
    Inject-LoaderHeader $agentsFile "~/.config/opencode/rules" "Agent Instructions"
  } else {
    Ensure-Dir (Split-Path -Parent $agentsFile)
    # Create new AGENTS.md with loader header
    $block = @"
$markerBegin
# Agent Instructions

At the start of every conversation, preload these rule files (they define mandatory protocols):
1. `~/.config/opencode/rules/00-init.md` -- Global Operating System. Always active. Defines universal mandates that supersede individual expert personas. Don't skip this.
2. `~/.config/opencode/rules/01-router.md` -- MoE Router. Front-line triage. Analyzes intent and routes to the correct expert or pipeline.

These files establish the core protocol: routing before acting, logging all command output, labeling uncertainty (VERIFIED/HYPOTHESIS), and following the definition of done.
$markerEnd
"@
    Set-Content -Path $agentsFile -Value $block -NoNewline
    Write-Host "    Loader:   $agentsFile"
  }
}

function Install-Gemini {
  Copy-GlobToDest (Join-Path $srcGemini "*.md") $destGemini "Gemini"
  # Write custom GEMINI.md with tool-specific loader protocol (non-destructive: only if file exists)
  $geminiMd = Join-Path $homeDir ".gemini/GEMINI.md"
  if (Test-Path $geminiMd) {
    # Backup existing file
    $backup = "$geminiMd.bak.$(Get-Date -Format 'yyyyMMddHHmmss')"
    Copy-Item -Path $geminiMd -Destination $backup -Force
    Write-Host "    Backup:   $backup"
    # Replace the loader block in existing file
    $content = Get-Content -Path $geminiMd -Raw
    $newBlock = @"
$markerBegin
# CRITICAL: MANDATORY BOOT PROTOCOL
Before generating ANY response or answering ANY user inquiry in the first turn, you MUST execute the following sequence:

1. **Preload & Audit:** In parallel, call `read_file` for `~/.gemini/rules/00-init.md` and `~/.gemini/rules/01-router.md`, and `list_directory` for `~/.gemini/rules/` to verify the expert roster against the filesystem.
2. **Initialize Logging:** Execute `mkdir -p .logs` via `run_shell_command` to ensure the Non-Destructive Logging Protocol is viable immediately.
3. **Verification:** Confirm the `[rules:loaded...]` token is present and expert files match the expected roster.
4. **Response Barrier:** Do not provide any conversational output until all tools above have returned and verification is complete.

Failure to perform this sequence is a violation of the System Integrity mandate.

$markerEnd
"@
    if ($content.Contains($markerBegin) -and $content.Contains($markerEnd)) {
      $start = $content.IndexOf($markerBegin)
      $finish = $content.IndexOf($markerEnd, $start)
      if ($start -ge 0 -and $finish -ge 0) {
        $finish = $finish + $markerEnd.Length
        if ($finish -lt $content.Length -and $content[$finish] -eq "`n") { $finish += 1 }
        $updated = $content.Substring(0, $start) + $newBlock + "`n" + $content.Substring($finish)
        Set-Content -Path $geminiMd -Value $updated -NoNewline
      }
    } else {
      Set-Content -Path $geminiMd -Value ($newBlock + "`n`n" + $content) -NoNewline
    }
    Write-Host "    Loader:   $geminiMd (updated)"
  } else {
    Ensure-Dir (Split-Path -Parent $geminiMd)
    $newBlock = @"
$markerBegin
# CRITICAL: MANDATORY BOOT PROTOCOL
Before generating ANY response or answering ANY user inquiry in the first turn, you MUST execute the following sequence:

1. **Preload & Audit:** In parallel, call `read_file` for `~/.gemini/rules/00-init.md` and `~/.gemini/rules/01-router.md`, and `list_directory` for `~/.gemini/rules/` to verify the expert roster against the filesystem.
2. **Initialize Logging:** Execute `mkdir -p .logs` via `run_shell_command` to ensure the Non-Destructive Logging Protocol is viable immediately.
3. **Verification:** Confirm the `[rules:loaded...]` token is present and expert files match the expected roster.
4. **Response Barrier:** Do not provide any conversational output until all tools above have returned and verification is complete.

Failure to perform this sequence is a violation of the System Integrity mandate.

$markerEnd
"@
    Set-Content -Path $geminiMd -Value $newBlock -NoNewline
    Write-Host "    Loader:   $geminiMd (created)"
  }
}

function List-Claude {
  Write-Host "    Claude (~/.claude/rules/):"
  $files = Get-ChildItem -Path (Join-Path $srcClaude "*.md") -File -ErrorAction SilentlyContinue
  foreach ($f in $files) {
    $target = Join-Path $destClaude $f.Name
    $status = if (Test-Path $target) { "installed" } else { "not found" }
    Write-Host "      $target  [$status]"
  }
  $cstatus = if (Test-Path (Join-Path $homeDir ".claude/CLAUDE.md")) { "installed" } else { "not found" }
  Write-Host "      CLaude.md  [$cstatus]"
}

function List-Cursor {
  Write-Host "    Cursor (~/.cursor/rules/):"
  $files = Get-ChildItem -Path (Join-Path $srcCursor "*.mdc") -File -ErrorAction SilentlyContinue
  foreach ($f in $files) {
    $target = Join-Path $destCursor $f.Name
    $status = if (Test-Path $target) { "installed" } else { "not found" }
    Write-Host "      $target  [$status]"
  }
}

function List-Windsurf {
  Write-Host "    Windsurf (~/.windsurf/rules/):"
  $files = Get-ChildItem -Path (Join-Path $srcWindsurf "*.md") -File -ErrorAction SilentlyContinue
  foreach ($f in $files) {
    $target = Join-Path $destWindsurf $f.Name
    $status = if (Test-Path $target) { "installed" } else { "not found" }
    Write-Host "      $target  [$status]"
  }
  $wstatus = if (Test-Path (Join-Path $homeDir ".windsurf/WINDSURF.md")) { "installed" } else { "not found" }
  Write-Host "      WINDSURF.md  [$wstatus]"
}

function List-Codex {
  Write-Host "    Codex (~/.codex/):"
  $target = Join-Path $destCodex "AGENTS.md"
  $status = if (Test-Path $target) { "installed" } else { "not found" }
  Write-Host "      $target  [$status]"
}

function List-Crush {
  Write-Host "    Crush (~/.config/crush/rules/):"
  $files = Get-ChildItem -Path (Join-Path $srcCrush "*.md") -File -ErrorAction SilentlyContinue
  foreach ($f in $files) {
    $target = Join-Path $destCrush $f.Name
    $status = if (Test-Path $target) { "installed" } else { "not found" }
    Write-Host "      $target  [$status]"
  }
  $cstatus = if (Test-Path $crushMd) { "installed" } else { "not found" }
  Write-Host "      $crushMd  [$cstatus]"
}

function List-OpenCode {
  Write-Host "    OpenCode (~/.config/opencode/rules/):"
  $files = Get-ChildItem -Path (Join-Path $srcOpenCode "*.md") -File -ErrorAction SilentlyContinue
  foreach ($f in $files) {
    $target = Join-Path $destOpenCode $f.Name
    $status = if (Test-Path $target) { "installed" } else { "not found" }
    Write-Host "      $target  [$status]"
  }
  $astatus = if (Test-Path $openCodeAgents) { "installed" } else { "not found" }
  Write-Host "      $openCodeAgents  [$astatus]"
}

function List-Gemini {
  Write-Host "    Gemini (~/.gemini/rules/):"
  $files = Get-ChildItem -Path (Join-Path $srcGemini "*.md") -File -ErrorAction SilentlyContinue
  foreach ($f in $files) {
    $target = Join-Path $destGemini $f.Name
    $status = if (Test-Path $target) { "installed" } else { "not found" }
    Write-Host "      $target  [$status]"
  }
  $gmstatus = if (Test-Path $geminiMd) { "installed" } else { "not found" }
  Write-Host "      $geminiMd  [$gmstatus]"
}

function Detect-Targets {
  $detected = @()
  if (Test-Path (Join-Path $homeDir ".claude")) { $detected += "claude" }
  if (Test-Path (Join-Path $homeDir ".cursor")) { $detected += "cursor" }
  if ((Test-Path (Join-Path $homeDir ".windsurf")) -or (Test-Path (Join-Path $homeDir ".codeium/windsurf"))) { $detected += "windsurf" }
  if (Test-Path (Join-Path $homeDir ".codex")) { $detected += "codex" }
  if ((Test-Path (Join-Path $appData "crush")) -or (Test-Path (Join-Path $homeDir ".config/crush"))) { $detected += "crush" }
  if ((Test-Path (Join-Path $appData "opencode")) -or (Test-Path (Join-Path $homeDir ".config/opencode"))) { $detected += "opencode" }
  if (Test-Path (Join-Path $homeDir ".gemini")) { $detected += "gemini" }
  return $detected
}

# Optional build step
$buildScript = Join-Path $repoDir "scripts/build-prompt-system.mjs"
if (Test-Path $buildScript) {
  Write-Host "--> Building prompt system..."
  $buildArgs = @($buildScript)
  if ($debug) { $buildArgs += "--debug" }
  if ($scaffolded) { $buildArgs += "--scaffolded" }
  Push-Location $repoDir
  try {
    & node @buildArgs
  }
  finally {
    Pop-Location
  }
  Write-Host ""
}

if (-not (Test-Path $srcClaude)) {
  throw "ERROR: Generated files not found and no build script available."
}

$targets = New-Object System.Collections.Generic.List[string]
if ($all) {
  @("claude", "cursor", "windsurf", "codex", "crush", "opencode", "gemini") | ForEach-Object { [void]$targets.Add($_) }
} else {
  if ($claude) { [void]$targets.Add("claude") }
  if ($cursor) { [void]$targets.Add("cursor") }
  if ($windsurf) { [void]$targets.Add("windsurf") }
  if ($codex) { [void]$targets.Add("codex") }
  if ($crush) { [void]$targets.Add("crush") }
  if ($opencode) { [void]$targets.Add("opencode") }
  if ($gemini) { [void]$targets.Add("gemini") }
}

if ($targets.Count -eq 0) {
  Detect-Targets | ForEach-Object { [void]$targets.Add($_) }
}

if ($targets.Count -eq 0) {
  throw "ERROR: No supported editors detected. Use --claude, --cursor, --windsurf, --codex, --crush, --opencode, or --gemini."
}

if ($list) {
  Write-Host "==> agent-historic installed files"
  Write-Host "    Targets: $($targets -join ' ')"
  Write-Host ""
  foreach ($t in $targets) {
    switch ($t) {
      "claude" { List-Claude }
      "cursor" { List-Cursor }
      "windsurf" { List-Windsurf }
      "codex" { List-Codex }
      "crush" { List-Crush }
      "opencode" { List-OpenCode }
      "gemini" { List-Gemini }
    }
    Write-Host ""
  }
  Write-Host "==> No files were modified."
  exit 0
}

Write-Host "==> agent-historic persona install"
Write-Host "    Source:  $repoDir"
Write-Host "    Targets: $($targets -join ' ')"
Write-Host "    Style:   rich (universal default)"
Write-Host ""
Write-Host "--> Installing rules..."

foreach ($t in $targets) {
  switch ($t) {
    "claude" { Install-Claude }
    "cursor" { Install-Cursor }
    "windsurf" { Install-Windsurf }
    "codex" { Install-Codex }
    "crush" { Install-Crush }
    "opencode" { Install-OpenCode }
    "gemini" { Install-Gemini }
  }
}

Write-Host ""
Write-Host "==> Done."