#!/usr/bin/env bash
# install.sh -- Install Agent Historic persona rules into AI coding editors
# Run from the project root: bash install.sh [--claude] [--cursor] [--windsurf] [--codex] [--all]
# Use --gpt to install sparse/GPT-optimized rules for Cursor and Windsurf instead of rich
# No flags = auto-detect installed editors

set -e

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"

# --- Source directories (generated by: node scripts/build-prompt-system.mjs) ---
SRC_CLAUDE="$REPO_DIR/dot-claude/rules"
SRC_CURSOR="$REPO_DIR/dot-cursor/rules"
SRC_CURSOR_GPT="$REPO_DIR/dot-cursor/rules/gpt"
SRC_WINDSURF="$REPO_DIR/dot-windsurf/rules"
SRC_WINDSURF_GPT="$REPO_DIR/dot-windsurf/rules/gpt"
SRC_CODEX="$REPO_DIR/dot-codex"

# --- Target directories (user home) ---
DEST_CLAUDE="$HOME/.claude/rules"
DEST_CURSOR="$HOME/.cursor/rules"
DEST_WINDSURF="$HOME/.windsurf/rules"
DEST_CODEX="$HOME/.codex"

# --- Backup ---

backup_dir() {
  local dir="$1"
  if [[ -d "$dir" ]]; then
    local ts
    ts="$(date +%Y%m%d-%H%M%S)"
    cp -r "$dir" "${dir}-${ts}"
    echo "    Backup: ${dir}-${ts}"
  fi
}

# --- Install functions ---

install_claude() {
  mkdir -p "$DEST_CLAUDE"
  for f in "$SRC_CLAUDE"/*.md; do
    [[ -f "$f" ]] || continue
    cp "$f" "$DEST_CLAUDE/$(basename "$f")"
    echo "    Claude:   $DEST_CLAUDE/$(basename "$f")"
  done
}

install_cursor() {
  mkdir -p "$DEST_CURSOR"
  # Rich rules at root (universal default)
  for f in "$SRC_CURSOR"/*.mdc; do
    [[ -f "$f" ]] || continue
    cp "$f" "$DEST_CURSOR/$(basename "$f")"
    echo "    Cursor:   $DEST_CURSOR/$(basename "$f")"
  done
  # GPT/sparse rules (only with --gpt)
  if [[ "$USE_GPT" == true ]]; then
    mkdir -p "$DEST_CURSOR/gpt"
    for f in "$SRC_CURSOR_GPT"/*.mdc; do
      [[ -f "$f" ]] || continue
      cp "$f" "$DEST_CURSOR/gpt/$(basename "$f")"
      echo "    Cursor:   $DEST_CURSOR/gpt/$(basename "$f") (sparse/deprecated)"
    done
  fi
}

install_windsurf() {
  mkdir -p "$DEST_WINDSURF"
  # Rich rules at root (universal default)
  for f in "$SRC_WINDSURF"/*.md; do
    [[ -f "$f" ]] || continue
    cp "$f" "$DEST_WINDSURF/$(basename "$f")"
    echo "    Windsurf: $DEST_WINDSURF/$(basename "$f")"
  done
  # GPT/sparse rules (only with --gpt)
  if [[ "$USE_GPT" == true ]]; then
    mkdir -p "$DEST_WINDSURF/gpt"
    for f in "$SRC_WINDSURF_GPT"/*.md; do
      [[ -f "$f" ]] || continue
      cp "$f" "$DEST_WINDSURF/gpt/$(basename "$f")"
      echo "    Windsurf: $DEST_WINDSURF/gpt/$(basename "$f") (sparse/deprecated)"
    done
  fi
}

install_codex() {
  mkdir -p "$DEST_CODEX"
  cp -r "$SRC_CODEX"/* "$DEST_CODEX/"
  echo "    Codex:    $DEST_CODEX/"
}

# --- List functions ---

list_claude() {
  echo "    Claude (~/.claude/rules/):"
  for f in "$SRC_CLAUDE"/*.md; do
    [[ -f "$f" ]] || continue
    local name
    name="$(basename "$f")"
    local dest="$DEST_CLAUDE/$name"
    local status="not found"
    [[ -f "$dest" ]] && status="installed"
    echo "      $dest  [$status]"
  done
}

list_cursor() {
  echo "    Cursor (~/.cursor/rules/):"
  for f in "$SRC_CURSOR"/*.mdc; do
    [[ -f "$f" ]] || continue
    local name
    name="$(basename "$f")"
    local dest="$DEST_CURSOR/$name"
    local status="not found"
    [[ -f "$dest" ]] && status="installed"
    echo "      $dest  [$status]"
  done
}

list_windsurf() {
  echo "    Windsurf (~/.windsurf/rules/):"
  for f in "$SRC_WINDSURF"/*.md; do
    [[ -f "$f" ]] || continue
    local name
    name="$(basename "$f")"
    local dest="$DEST_WINDSURF/$name"
    local status="not found"
    [[ -f "$dest" ]] && status="installed"
    echo "      $dest  [$status]"
  done
}

list_codex() {
  echo "    Codex (~/.codex/):"
  local dest="$DEST_CODEX/AGENTS.md"
  local status="not found"
  [[ -f "$dest" ]] && status="installed"
  echo "      $dest  [$status]"
}

# --- Auto-detection ---

detect_editors() {
  local detected=()
  [[ -d "$HOME/.claude" ]] && detected+=("claude")
  [[ -d "$HOME/.cursor" ]] && detected+=("cursor")
  [[ -d "$HOME/.windsurf" || -d "$HOME/.codeium/windsurf" ]] && detected+=("windsurf")
  [[ -d "$HOME/.codex" ]] && detected+=("codex")
  echo "${detected[@]}"
}

# --- Post-install notes ---

print_post_install() {
  echo ""
  echo "=== POST-INSTALL: REQUIRED IDE CONFIGURATION ==="
  echo ""
  echo "  Rich rules are installed as the universal default for all models."
  if [[ "$USE_GPT" == true ]]; then
    echo "  Sparse/GPT rules also installed in gpt/ subfolder (deprecated)."
  fi
  echo ""

  for target in "$@"; do
    case "$target" in
      claude)
        echo "  Claude Code"
        echo "    Rules auto-loaded from ~/.claude/rules/ — no extra config needed."
        echo ""
        ;;
      cursor)
        echo "  Cursor (IMPORTANT)"
        echo "    1. Open Cursor Settings > Rules for AI"
        echo "    2. 00-init must load on every request (alwaysApply: true)."
        echo "    3. 01-router must load on every request (alwaysApply: true)."
        echo "    4. Expert rules (expert-*.mdc) are auto-attached by Cursor"
        echo "       when their description matches the conversation context."
        echo "    Files: ~/.cursor/rules/"
        echo ""
        ;;
      windsurf)
        echo "  Windsurf (IMPORTANT)"
        echo "    1. Open Windsurf > Customizations > Rules"
        echo "    2. 00-init.md has trigger: always — global runtime."
        echo "    3. 01-router.md has trigger: always — request triage."
        echo "    4. Expert rules use trigger: model_decision — Cascade reads"
        echo "       them automatically when the description matches."
        echo "    Files: ~/.windsurf/rules/"
        echo ""
        ;;
      codex)
        echo "  Codex"
        echo "    AGENTS.md and skills/ are installed to ~/.codex/."
        echo "    No extra config needed."
        echo ""
        ;;
    esac
  done

  echo "  Tip: Run 'bash install.sh --list' to verify installed files."
  echo ""
}

# --- CLI parsing ---

TARGETS=()
DO_LIST=false
USE_GPT=false
DEBUG_MODE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --claude)    TARGETS+=("claude"); shift ;;
    --cursor)    TARGETS+=("cursor"); shift ;;
    --windsurf)  TARGETS+=("windsurf"); shift ;;
    --codex)     TARGETS+=("codex"); shift ;;
    --all)       TARGETS=("claude" "cursor" "windsurf" "codex"); shift ;;
    # --gpt installs deprecated sparse rules alongside rich (opt-in)
    --gpt)       USE_GPT=true; shift ;;
    --list)      DO_LIST=true; shift ;;
    --debug)     DEBUG_MODE=true; shift ;;
    --help|-h)
      echo "Usage: bash install.sh [options]"
      echo ""
      echo "Options:"
      echo "  --claude       Install rules for Claude Code"
      echo "  --cursor       Install rules for Cursor"
      echo "  --windsurf     Install rules for Windsurf"
      echo "  --codex        Install rules for Codex"
      echo "  --all          Install for all editors"
      echo "  --gpt          [DEPRECATED] Also install sparse/GPT-optimized rules in gpt/ subfolder"
      echo "                 Rich rules are now the universal default for all models."
      echo "  --list         List installed files and their status (no changes made)"
      echo "  --debug        Include self-identification routing preamble in generated rules"
      echo "  -h, --help     Show this help"
      echo ""
      echo "No flags = auto-detect installed editors."
      echo ""
      echo "Before running, generate the prompt files:"
      echo "  node scripts/build-prompt-system.mjs"
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      echo "Run: bash install.sh --help"
      exit 1
      ;;
  esac
done

# --- Build ---

if [[ -f "$REPO_DIR/scripts/build-prompt-system.mjs" ]]; then
  echo "--> Building prompt system..."
  if $DEBUG_MODE; then
    node "$REPO_DIR/scripts/build-prompt-system.mjs" --debug
  else
    node "$REPO_DIR/scripts/build-prompt-system.mjs"
  fi
  echo ""
fi

if [[ ! -d "$SRC_CLAUDE" ]]; then
  echo "ERROR: Generated files not found and no build script available."
  exit 1
fi

# --- Auto-detect if no targets specified ---

if [[ ${#TARGETS[@]} -eq 0 ]]; then
  read -ra TARGETS <<< "$(detect_editors)"
fi

if [[ ${#TARGETS[@]} -eq 0 ]]; then
  echo "ERROR: No supported editors detected. Use --claude, --cursor, --windsurf, or --codex."
  exit 1
fi

# --- List path ---

if [[ "$DO_LIST" == true ]]; then
  echo "==> agent-historic installed files"
  echo "    Targets: ${TARGETS[*]}"
  echo ""
  for target in "${TARGETS[@]}"; do
    "list_${target}"
    echo ""
  done
  echo "==> No files were modified."
  exit 0
fi

# --- Install path ---

echo "==> agent-historic persona install"
echo "    Source:  $REPO_DIR"
echo "    Targets: ${TARGETS[*]}"
echo "    Style:   rich (universal default)"
echo ""

echo "--> Backing up existing rule directories..."
for target in "${TARGETS[@]}"; do
  case "$target" in
    claude)   backup_dir "$DEST_CLAUDE" ;;
    cursor)   backup_dir "$DEST_CURSOR" ;;
    windsurf) backup_dir "$DEST_WINDSURF" ;;
    codex)    backup_dir "$DEST_CODEX" ;;
  esac
done

echo "--> Installing rules..."
for target in "${TARGETS[@]}"; do
  "install_${target}"
done

echo ""
echo "==> Done."

print_post_install "${TARGETS[@]}"
