#!/usr/bin/env pwsh
# install-local.ps1 -- Install Agent Historic persona rules into AI coding editors on Windows/PowerShell.
# Usage: pwsh -File .\install-local.ps1 [--claude] [--cursor] [--windsurf] [--codex] [--opencode] [--all]
# No flags = auto-detect installed editors.

param(
  [switch]$claude,
  [switch]$cursor,
  [switch]$windsurf,
  [switch]$codex,
  [switch]$opencode,
  [switch]$all,
  [switch]$list,
  [switch]$debug,
  [switch]$scaffolded,
  [switch]$help
)

$ErrorActionPreference = "Stop"

if ($help) {
  Write-Host "Usage: pwsh -File .\install-local.ps1 [options]"
  Write-Host ""
  Write-Host "Options:"
  Write-Host "  --claude       Install rules for Claude Code"
  Write-Host "  --cursor       Install rules for Cursor"
  Write-Host "  --windsurf     Install rules for Windsurf"
  Write-Host "  --codex        Install rules for Codex"
  Write-Host "  --opencode     Install rules for OpenCode"
  Write-Host "  --all          Install for all editors"
  Write-Host "  --list         List installed files and their status (no changes made)"
  Write-Host "  --scaffolded   Use scaffolded voice during build"
  Write-Host "  --debug        Include debug routing preamble during build"
  Write-Host "  --help         Show this help"
  Write-Host ""
  Write-Host "No flags = auto-detect installed editors."
  exit 0
}

$repoDir = Split-Path -Parent $MyInvocation.MyCommand.Path

# Source directories (generated by scripts/build-prompt-system.mjs)
$srcClaude = Join-Path $repoDir "compiled/claude/rules"
$srcCursor = Join-Path $repoDir "compiled/cursor/rules"
$srcWindsurf = Join-Path $repoDir "compiled/windsurf/rules"
$srcCodex = Join-Path $repoDir "compiled/codex"
$srcOpenCode = $srcClaude

# Target directories (Windows defaults)
$homeDir = $HOME
$appData = $env:APPDATA
$destClaude = Join-Path $homeDir ".claude/rules"
$destCursor = Join-Path $homeDir ".cursor/rules"
$destWindsurf = Join-Path $homeDir ".windsurf/rules"
$destCodex = Join-Path $homeDir ".codex"
$destOpenCode = if ($appData) { Join-Path $appData "opencode/rules" } else { Join-Path $homeDir ".config/opencode/rules" }
$openCodeAgents = if ($appData) { Join-Path $appData "opencode/AGENTS.md" } else { Join-Path $homeDir ".config/opencode/AGENTS.md" }

$managedMarker = "managed_by: agent-historic"
$markerBegin = "<!-- agent-historic:loader-begin -->"
$markerEnd = "<!-- agent-historic:loader-end -->"

function Ensure-Dir([string]$path) {
  if (-not (Test-Path $path)) {
    New-Item -ItemType Directory -Path $path -Force | Out-Null
  }
}

function Cleanup-ManagedFiles([string]$destDir) {
  if (-not (Test-Path $destDir)) { return }
  Get-ChildItem -Path $destDir -Recurse -File -ErrorAction SilentlyContinue | ForEach-Object {
    $f = $_.FullName
    if (Select-String -Path $f -Pattern ([Regex]::Escape($managedMarker)) -Quiet -ErrorAction SilentlyContinue) {
      Remove-Item -Path $f -Force
      Write-Host "    Removed stale: $f"
    }
  }
}

function Inject-LoaderHeader([string]$file, [string]$rulesDir, [string]$title) {
  $block = @"
$markerBegin
# $title

Always load and apply the following rule files from `$rulesDir at the start of every conversation:

1. `$rulesDir/00-init.md` -- Global runtime (constraints, logging, voice, definition of done)
2. `$rulesDir/01-router.md` -- MoE router (expert selection, pipelines, disambiguation)

These two files are always active. All other expert files in `$rulesDir are activated by model decision based on their description field.
$markerEnd
"@

  $content = ""
  if (Test-Path $file) {
    $content = Get-Content -Path $file -Raw
  } else {
    Ensure-Dir (Split-Path -Parent $file)
  }

  if ($content.Contains($markerBegin) -and $content.Contains($markerEnd)) {
    $start = $content.IndexOf($markerBegin)
    $finish = $content.IndexOf($markerEnd, $start)
    if ($start -ge 0 -and $finish -ge 0) {
      $finish = $finish + $markerEnd.Length
      if ($finish -lt $content.Length -and $content[$finish] -eq "`n") {
        $finish += 1
      }
      $updated = $content.Substring(0, $start) + $block + "`n" + $content.Substring($finish)
      Set-Content -Path $file -Value $updated -NoNewline
    }
  } elseif ([string]::IsNullOrWhiteSpace($content)) {
    Set-Content -Path $file -Value $block -NoNewline
  } else {
    Set-Content -Path $file -Value ($block + "`n`n" + $content) -NoNewline
  }

  Write-Host "    Loader:   $file"
}

function Copy-GlobToDest([string]$pattern, [string]$dest, [string]$label) {
  Ensure-Dir $dest
  Cleanup-ManagedFiles $dest
  $files = Get-ChildItem -Path $pattern -File -ErrorAction SilentlyContinue
  foreach ($f in $files) {
    Copy-Item -Path $f.FullName -Destination (Join-Path $dest $f.Name) -Force
    Write-Host ("    {0,-9} {1}" -f ($label + ":"), (Join-Path $dest $f.Name))
  }
}

function Install-Claude {
  Copy-GlobToDest (Join-Path $srcClaude "*.md") $destClaude "Claude"
  Inject-LoaderHeader (Join-Path $homeDir ".claude/CLAUDE.md") "~/.claude/rules" "Claude Code Instructions"
}

function Install-Cursor {
  Copy-GlobToDest (Join-Path $srcCursor "*.mdc") $destCursor "Cursor"
}

function Install-Windsurf {
  Copy-GlobToDest (Join-Path $srcWindsurf "*.md") $destWindsurf "Windsurf"
}

function Install-Codex {
  Ensure-Dir $destCodex
  Cleanup-ManagedFiles $destCodex
  Copy-Item -Path (Join-Path $srcCodex "*") -Destination $destCodex -Recurse -Force
  Write-Host "    Codex:    $destCodex"
}

function Install-OpenCode {
  Copy-GlobToDest (Join-Path $srcOpenCode "*.md") $destOpenCode "OpenCode"
  Inject-LoaderHeader $openCodeAgents "~/.config/opencode/rules" "Agent Instructions"
}

function List-GlobStatus([string]$pattern, [string]$dest, [string]$title) {
  Write-Host "    $title"
  $files = Get-ChildItem -Path $pattern -File -ErrorAction SilentlyContinue
  foreach ($f in $files) {
    $target = Join-Path $dest $f.Name
    $status = if (Test-Path $target) { "installed" } else { "not found" }
    Write-Host "      $target  [$status]"
  }
}

function List-Claude { List-GlobStatus (Join-Path $srcClaude "*.md")  $destClaude   "Claude (~/.claude/rules/):" }
function List-Cursor { List-GlobStatus (Join-Path $srcCursor "*.mdc")  $destCursor   "Cursor (~/.cursor/rules/):" }
function List-Windsurf { List-GlobStatus (Join-Path $srcWindsurf "*.md") $destWindsurf "Windsurf (~/.windsurf/rules/):" }
function List-Codex {
  Write-Host "    Codex (~/.codex/):"
  $target = Join-Path $destCodex "AGENTS.md"
  $status = if (Test-Path $target) { "installed" } else { "not found" }
  Write-Host "      $target  [$status]"
}
function List-OpenCode {
  Write-Host "    OpenCode (%APPDATA%\\opencode\\rules\\):"
  $files = Get-ChildItem -Path (Join-Path $srcOpenCode "*.md") -File -ErrorAction SilentlyContinue
  foreach ($f in $files) {
    $target = Join-Path $destOpenCode $f.Name
    $status = if (Test-Path $target) { "installed" } else { "not found" }
    Write-Host "      $target  [$status]"
  }
  $astatus = if (Test-Path $openCodeAgents) { "installed" } else { "not found" }
  Write-Host "      $openCodeAgents  [$astatus]"
}

function Detect-Targets {
  $detected = @()
  if (Test-Path (Join-Path $homeDir ".claude")) { $detected += "claude" }
  if (Test-Path (Join-Path $homeDir ".cursor")) { $detected += "cursor" }
  if (Test-Path (Join-Path $homeDir ".windsurf") -or Test-Path (Join-Path $homeDir ".codeium/windsurf")) { $detected += "windsurf" }
  if (Test-Path (Join-Path $homeDir ".codex")) { $detected += "codex" }
  if ((Test-Path (Join-Path $appData "opencode")) -or (Test-Path (Join-Path $homeDir ".config/opencode"))) { $detected += "opencode" }
  return $detected
}

# Optional build step
$buildScript = Join-Path $repoDir "scripts/build-prompt-system.mjs"
if (Test-Path $buildScript) {
  Write-Host "--> Building prompt system..."
  $buildArgs = @($buildScript)
  if ($debug) { $buildArgs += "--debug" }
  if ($scaffolded) { $buildArgs += "--scaffolded" }
  Push-Location $repoDir
  try {
    & node @buildArgs
  }
  finally {
    Pop-Location
  }
  Write-Host ""
}

if (-not (Test-Path $srcClaude)) {
  throw "ERROR: Generated files not found and no build script available."
}

$targets = New-Object System.Collections.Generic.List[string]
if ($all) {
  @("claude", "cursor", "windsurf", "codex", "opencode") | ForEach-Object { [void]$targets.Add($_) }
} else {
  if ($claude) { [void]$targets.Add("claude") }
  if ($cursor) { [void]$targets.Add("cursor") }
  if ($windsurf) { [void]$targets.Add("windsurf") }
  if ($codex) { [void]$targets.Add("codex") }
  if ($opencode) { [void]$targets.Add("opencode") }
}

if ($targets.Count -eq 0) {
  Detect-Targets | ForEach-Object { [void]$targets.Add($_) }
}

if ($targets.Count -eq 0) {
  throw "ERROR: No supported editors detected. Use --claude, --cursor, --windsurf, --codex, or --opencode."
}

if ($list) {
  Write-Host "==> agent-historic installed files"
  Write-Host "    Targets: $($targets -join ' ')"
  Write-Host ""
  foreach ($t in $targets) {
    switch ($t) {
      "claude" { List-Claude }
      "cursor" { List-Cursor }
      "windsurf" { List-Windsurf }
      "codex" { List-Codex }
      "opencode" { List-OpenCode }
    }
    Write-Host ""
  }
  Write-Host "==> No files were modified."
  exit 0
}

Write-Host "==> agent-historic persona install"
Write-Host "    Source:  $repoDir"
Write-Host "    Targets: $($targets -join ' ')"
Write-Host "    Style:   rich (universal default)"
Write-Host ""
Write-Host "--> Installing rules..."

foreach ($t in $targets) {
  switch ($t) {
    "claude" { Install-Claude }
    "cursor" { Install-Cursor }
    "windsurf" { Install-Windsurf }
    "codex" { Install-Codex }
    "opencode" { Install-OpenCode }
  }
}

Write-Host ""
Write-Host "==> Done."
