#!/usr/bin/env bash
# install.sh -- Install philosopher prompt system rules into AI coding editors
# Run from the project root: bash install.sh [--claude] [--cursor] [--windsurf] [--codex] [--all]
# Use --gpt to install sparse/GPT-optimized rules for Cursor and Windsurf instead of rich
# No flags = auto-detect installed editors

set -e

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"

# --- Source directories (generated by: node scripts/build-prompt-system.mjs) ---
SRC_CLAUDE="$REPO_DIR/dot-claude/rules"
SRC_CURSOR="$REPO_DIR/dot-cursor/rules"
SRC_CURSOR_RICH="$REPO_DIR/dot-cursor/rules/rich"
SRC_CURSOR_GPT="$REPO_DIR/dot-cursor/rules/gpt"
SRC_WINDSURF="$REPO_DIR/dot-windsurf/rules"
SRC_WINDSURF_RICH="$REPO_DIR/dot-windsurf/rules/rich"
SRC_WINDSURF_GPT="$REPO_DIR/dot-windsurf/rules/gpt"
SRC_CODEX="$REPO_DIR/dot-codex"

# --- Target directories (user home) ---
DEST_CLAUDE="$HOME/dot-claude/rules"
DEST_CURSOR="$HOME/dot-cursor/rules"
DEST_WINDSURF="$HOME/dot-windsurf/rules"
DEST_CODEX="$HOME/dot-codex"

# --- Backup ---

backup_dir() {
  local dir="$1"
  if [[ -d "$dir" ]]; then
    local ts
    ts="$(date +%Y%m%d-%H%M%S)"
    cp -r "$dir" "${dir}-${ts}"
    echo "    Backup: ${dir}-${ts}"
  fi
}

# --- Install functions ---

install_claude() {
  mkdir -p "$DEST_CLAUDE"
  for f in "$SRC_CLAUDE"/*.md; do
    [[ -f "$f" ]] || continue
    cp "$f" "$DEST_CLAUDE/$(basename "$f")"
    echo "    Claude:   $DEST_CLAUDE/$(basename "$f")"
  done
}

install_cursor() {
  mkdir -p "$DEST_CURSOR"
  # Startup loader at root
  if [[ -f "$SRC_CURSOR/00-startup.mdc" ]]; then
    cp "$SRC_CURSOR/00-startup.mdc" "$DEST_CURSOR/00-startup.mdc"
    echo "    Cursor:   $DEST_CURSOR/00-startup.mdc"
  fi
  # Rich rules in rich/ subfolder
  mkdir -p "$DEST_CURSOR/rich"
  for f in "$SRC_CURSOR_RICH"/*.mdc; do
    [[ -f "$f" ]] || continue
    cp "$f" "$DEST_CURSOR/rich/$(basename "$f")"
    echo "    Cursor:   $DEST_CURSOR/rich/$(basename "$f")"
  done
  # GPT rules in gpt/ subfolder
  mkdir -p "$DEST_CURSOR/gpt"
  for f in "$SRC_CURSOR_GPT"/*.mdc; do
    [[ -f "$f" ]] || continue
    cp "$f" "$DEST_CURSOR/gpt/$(basename "$f")"
    echo "    Cursor:   $DEST_CURSOR/gpt/$(basename "$f")"
  done
}

install_windsurf() {
  mkdir -p "$DEST_WINDSURF"
  # Startup loader at root
  if [[ -f "$SRC_WINDSURF/00-startup.md" ]]; then
    cp "$SRC_WINDSURF/00-startup.md" "$DEST_WINDSURF/00-startup.md"
    echo "    Windsurf: $DEST_WINDSURF/00-startup.md"
  fi
  # Rich rules in rich/ subfolder
  mkdir -p "$DEST_WINDSURF/rich"
  for f in "$SRC_WINDSURF_RICH"/*.md; do
    [[ -f "$f" ]] || continue
    cp "$f" "$DEST_WINDSURF/rich/$(basename "$f")"
    echo "    Windsurf: $DEST_WINDSURF/rich/$(basename "$f")"
  done
  # GPT rules in gpt/ subfolder
  mkdir -p "$DEST_WINDSURF/gpt"
  for f in "$SRC_WINDSURF_GPT"/*.md; do
    [[ -f "$f" ]] || continue
    cp "$f" "$DEST_WINDSURF/gpt/$(basename "$f")"
    echo "    Windsurf: $DEST_WINDSURF/gpt/$(basename "$f")"
  done
}

install_codex() {
  mkdir -p "$DEST_CODEX"
  cp -r "$SRC_CODEX"/* "$DEST_CODEX/"
  echo "    Codex:    $DEST_CODEX/"
}

# --- List functions ---

list_claude() {
  echo "    Claude (~/dot-claude/rules/):"
  for f in "$SRC_CLAUDE"/*.md; do
    [[ -f "$f" ]] || continue
    local name
    name="$(basename "$f")"
    local dest="$DEST_CLAUDE/$name"
    local status="not found"
    [[ -f "$dest" ]] && status="installed"
    echo "      $dest  [$status]"
  done
}

list_cursor() {
  echo "    Cursor (~/dot-cursor/rules/):"
  for f in "$SRC_CURSOR"/*.mdc; do
    [[ -f "$f" ]] || continue
    local name
    name="$(basename "$f")"
    local dest="$DEST_CURSOR/$name"
    local status="not found"
    [[ -f "$dest" ]] && status="installed"
    echo "      $dest  [$status]"
  done
}

list_windsurf() {
  echo "    Windsurf (~/dot-windsurf/rules/):"
  for f in "$SRC_WINDSURF"/*.md; do
    [[ -f "$f" ]] || continue
    local name
    name="$(basename "$f")"
    local dest="$DEST_WINDSURF/$name"
    local status="not found"
    [[ -f "$dest" ]] && status="installed"
    echo "      $dest  [$status]"
  done
}

list_codex() {
  echo "    Codex (~/dot-codex/):"
  local dest="$DEST_CODEX/AGENTS.md"
  local status="not found"
  [[ -f "$dest" ]] && status="installed"
  echo "      $dest  [$status]"
}

# --- Auto-detection ---

detect_editors() {
  local detected=()
  [[ -d "$HOME/dot-claude" || -d "$HOME/.claude" ]] && detected+=("claude")
  [[ -d "$HOME/dot-cursor" || -d "$HOME/.cursor" ]] && detected+=("cursor")
  [[ -d "$HOME/dot-windsurf" || -d "$HOME/.windsurf" || -d "$HOME/.codeium/windsurf" ]] && detected+=("windsurf")
  [[ -d "$HOME/dot-codex" || -d "$HOME/.codex" ]] && detected+=("codex")
  echo "${detected[@]}"
}

# --- Post-install notes ---

print_post_install() {
  echo ""
  echo "=== POST-INSTALL: REQUIRED IDE CONFIGURATION ==="
  echo ""
  echo "  Both rich and sparse (gpt/) rules are installed."
  echo "  00-startup automatically directs GPT-family models to gpt/."
  echo ""

  for target in "$@"; do
    case "$target" in
      claude)
        echo "  Claude Code"
        echo "    Rules auto-loaded from ~/dot-claude/rules/ — no extra config needed."
        echo ""
        ;;
      cursor)
        echo "  Cursor (IMPORTANT)"
        echo "    1. Open Cursor Settings > Rules for AI"
        echo "    2. 00-startup.mdc must be the FIRST rule (alwaysApply: true)."
        echo "       It routes GPT models to the gpt/ subfolder automatically."
        echo "    3. 00-init must load on every request (alwaysApply: true)."
        echo "    4. 01-router must load on every request (alwaysApply: true)."
        echo "    5. Expert rules (expert-*.mdc) are auto-attached by Cursor"
        echo "       when their description matches the conversation context."
        echo "    Files: ~/dot-cursor/rules/ (rich) + ~/dot-cursor/rules/gpt/ (sparse)"
        echo ""
        ;;
      windsurf)
        echo "  Windsurf (IMPORTANT)"
        echo "    1. Open Windsurf > Customizations > Rules"
        echo "    2. 00-startup.md has trigger: always — routes GPT to gpt/."
        echo "    3. 00-init.md has trigger: always — global runtime."
        echo "    4. 01-router.md has trigger: always — request triage."
        echo "    5. Expert rules use trigger: model_decision — Cascade reads"
        echo "       them automatically when the description matches."
        echo "    Files: ~/dot-windsurf/rules/ (rich) + ~/dot-windsurf/rules/gpt/ (sparse)"
        echo ""
        ;;
      codex)
        echo "  Codex"
        echo "    AGENTS.md and skills/ are loaded automatically from ~/dot-codex/."
        echo "    No extra config needed."
        echo ""
        ;;
    esac
  done

  echo "  Tip: Run 'bash install.sh --list' to verify installed files."
  echo ""
}

# --- CLI parsing ---

TARGETS=()
DO_LIST=false
USE_GPT=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --claude)    TARGETS+=("claude"); shift ;;
    --cursor)    TARGETS+=("cursor"); shift ;;
    --windsurf)  TARGETS+=("windsurf"); shift ;;
    --codex)     TARGETS+=("codex"); shift ;;
    --all)       TARGETS=("claude" "cursor" "windsurf" "codex"); shift ;;
    # --gpt kept for backward compat but both sets always install now
    --gpt)       shift ;;
    --list)      DO_LIST=true; shift ;;
    --help|-h)
      echo "Usage: bash install.sh [options]"
      echo ""
      echo "Options:"
      echo "  --claude       Install rules for Claude Code"
      echo "  --cursor       Install rules for Cursor"
      echo "  --windsurf     Install rules for Windsurf"
      echo "  --codex        Install rules for Codex"
      echo "  --all          Install for all editors"
      echo "  --gpt          Use sparse/GPT-optimized rules for Cursor and Windsurf"
      echo "                 (Claude always gets rich; Codex always gets sparse)"
      echo "  --list         List installed files and their status (no changes made)"
      echo "  -h, --help     Show this help"
      echo ""
      echo "No flags = auto-detect installed editors."
      echo ""
      echo "Before running, generate the prompt files:"
      echo "  node scripts/build-prompt-system.mjs"
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      echo "Run: bash install.sh --help"
      exit 1
      ;;
  esac
done

# --- Pre-flight: ensure build output exists ---

if [[ ! -d "$SRC_CLAUDE" ]]; then
  echo "ERROR: Generated files not found. Run 'node scripts/build-prompt-system.mjs' first."
  exit 1
fi

# --- Auto-detect if no targets specified ---

if [[ ${#TARGETS[@]} -eq 0 ]]; then
  read -ra TARGETS <<< "$(detect_editors)"
fi

if [[ ${#TARGETS[@]} -eq 0 ]]; then
  echo "ERROR: No supported editors detected. Use --claude, --cursor, --windsurf, or --codex."
  exit 1
fi

# --- List path ---

if [[ "$DO_LIST" == true ]]; then
  echo "==> philosopher-system installed files"
  echo "    Targets: ${TARGETS[*]}"
  echo ""
  for target in "${TARGETS[@]}"; do
    "list_${target}"
    echo ""
  done
  echo "==> No files were modified."
  exit 0
fi

# --- Install path ---

echo "==> philosopher-system prompt install"
echo "    Source:  $REPO_DIR"
echo "    Targets: ${TARGETS[*]}"
echo "    Style:   rich + gpt/ subfolder (00-startup routes GPT models automatically)"
echo ""

echo "--> Backing up existing rule directories..."
for target in "${TARGETS[@]}"; do
  case "$target" in
    claude)   backup_dir "$DEST_CLAUDE" ;;
    cursor)   backup_dir "$DEST_CURSOR" ;;
    windsurf) backup_dir "$DEST_WINDSURF" ;;
    codex)    backup_dir "$DEST_CODEX" ;;
  esac
done

echo "--> Installing rules..."
for target in "${TARGETS[@]}"; do
  "install_${target}"
done

echo ""
echo "==> Done."

print_post_install "${TARGETS[@]}"
