#!/usr/bin/env bash
# install-local.sh -- Install Agent Historic persona rules into AI coding editors
# Run from the project root: bash install-local.sh [--claude] [--cursor] [--windsurf] [--codex] [--opencode] [--gemini] [--all]
# No flags = auto-detect installed editors

set -e

REPO_DIR="$(cd "$(dirname "$0")" && pwd)"

# --- Source directories (generated by: node scripts/build-prompt-system.mjs) ---
SRC_CLAUDE="$REPO_DIR/compiled/claude/rules"
SRC_CURSOR="$REPO_DIR/compiled/cursor/rules"
SRC_WINDSURF="$REPO_DIR/compiled/windsurf/rules"
SRC_CODEX="$REPO_DIR/compiled/codex"
SRC_CRUSH="$REPO_DIR/compiled/crush/rules"
SRC_OPENCODE="$SRC_CLAUDE"
SRC_GEMINI="$REPO_DIR/compiled/gemini/rules"

# --- Target directories (user home) ---
DEST_CLAUDE="$HOME/.claude/rules"
DEST_CURSOR="$HOME/.cursor/rules"
DEST_WINDSURF="$HOME/.windsurf/rules"
DEST_CODEX="$HOME/.codex"
DEST_CRUSH="$HOME/.config/crush/rules"
DEST_OPENCODE="$HOME/.config/opencode/rules"
DEST_GEMINI="$HOME/.gemini/rules"

# --- Managed-file marker (used for stale cleanup) ---
MANAGED_MARKER="managed_by: agent-historic"

cleanup_managed_files() {
  local dest_dir="$1"
  [[ -d "$dest_dir" ]] || return 0
  while IFS= read -r -d '' f; do
    rm "$f"
    echo "    Removed stale: $f"
  done < <(grep -rlZ "$MANAGED_MARKER" "$dest_dir" 2>/dev/null)
}

# --- Loader-header injection ---
# Writes (or replaces) a marked block at the top of a file that tells the IDE
# to always load the init + router rules. Idempotent: re-runs replace the block.
MARKER_BEGIN="<!-- agent-historic:loader-begin -->"
MARKER_END="<!-- agent-historic:loader-end -->"

inject_loader_header() {
  local file="$1"
  local rules_dir="$2"
  local title="$3"

  local block
  block="$(cat <<HEADER
$MARKER_BEGIN
# $title

At the start of every conversation, preload these rule files (they define mandatory protocols):
1. \`$rules_dir/00-init.md\` — Global Operating System. Always active. Defines universal mandates that supersede individual expert personas. Don't skip this.
2. \`$rules_dir/01-router.md\` — MoE Router. Front-line triage. Analyzes intent and routes to the correct expert or pipeline.

These files establish the core protocol: routing before acting, logging all command output, labeling uncertainty (VERIFIED/HYPOTHESIS), and following the definition of done.
$MARKER_END
HEADER
)"

  if [[ -f "$file" ]]; then
    if grep -q "$MARKER_BEGIN" "$file" 2>/dev/null; then
      # Replace the existing block between markers (inclusive)
      local tmp
      tmp="$(mktemp)"
      BLOCK="$block" MARKER_BEGIN="$MARKER_BEGIN" MARKER_END="$MARKER_END" TARGET_FILE="$file" python3 <<'PY' > "$tmp"
import os
from pathlib import Path

path = Path(os.environ["TARGET_FILE"])
content = path.read_text()
begin = os.environ["MARKER_BEGIN"]
end = os.environ["MARKER_END"]
block = os.environ["BLOCK"]

start = content.find(begin)
finish = content.find(end, start if start != -1 else 0)

if start != -1 and finish != -1:
    finish += len(end)
    if finish < len(content) and content[finish:finish + 1] == "\n":
        finish += 1
    updated = content[:start] + block + "\n" + content[finish:]
else:
    updated = block + "\n\n" + content

print(updated, end="")
PY
      mv "$tmp" "$file"
    else
      # Prepend block to existing content
      local tmp
      tmp="$(mktemp)"
      { echo "$block"; echo ""; cat "$file"; } > "$tmp"
      mv "$tmp" "$file"
    fi
  else
    mkdir -p "$(dirname "$file")"
    echo "$block" > "$file"
  fi
  echo "    Loader:   $file"
}

# --- Install functions ---

install_claude() {
  mkdir -p "$DEST_CLAUDE"
  cleanup_managed_files "$DEST_CLAUDE"
  for f in "$SRC_CLAUDE"/*.md; do
    [[ -f "$f" ]] || continue
    cp "$f" "$DEST_CLAUDE/$(basename "$f")"
    echo "    Claude:   $DEST_CLAUDE/$(basename "$f")"
  done
  inject_loader_header "$HOME/.claude/CLAUDE.md" "~/.claude/rules" "Claude Code Instructions"
}

install_cursor() {
  mkdir -p "$DEST_CURSOR"
  cleanup_managed_files "$DEST_CURSOR"
  # Rich rules at root (universal default)
  for f in "$SRC_CURSOR"/*.mdc; do
    [[ -f "$f" ]] || continue
    cp "$f" "$DEST_CURSOR/$(basename "$f")"
    echo "    Cursor:   $DEST_CURSOR/$(basename "$f")"
  done
}

install_windsurf() {
  mkdir -p "$DEST_WINDSURF"
  cleanup_managed_files "$DEST_WINDSURF"
  # Rich rules at root (universal default)
  for f in "$SRC_WINDSURF"/*.md; do
    [[ -f "$f" ]] || continue
    cp "$f" "$DEST_WINDSURF/$(basename "$f")"
    echo "    Windsurf: $DEST_WINDSURF/$(basename "$f")"
  done
  # Loader header injection for Windsurf project-level config
  inject_loader_header "$HOME/.windsurf/WINDSURF.md" "~/.windsurf/rules" "Windsurf Instructions"
  # Export global_rules.md to Windsurf memories for preload on every chat
  local ws_memories="$HOME/.codeium/windsurf/memories"
  mkdir -p "$ws_memories"
  local ws_global="$ws_memories/global_rules.md"
  cat > "$ws_global" <<EOF
# Load These First
At the start of every conversation, preload these rule files (they define mandatory protocols):
1. \`$HOME/.windsurf/rules/00-init.md\` — Global Operating System. Always active. Defines universal mandates that supersede individual expert personas. Don't skip this.
2. \`$HOME/.windsurf/rules/01-router.md\` — MoE Router. Front-line triage. Analyzes intent and routes to the correct expert or pipeline.
These files establish the core protocol: routing before acting, logging all command output, labeling uncertainty (VERIFIED/HYPOTHESIS), and following the definition of done.
EOF
  echo "    Memories: $ws_global"
}

install_codex() {
  mkdir -p "$DEST_CODEX"
  cleanup_managed_files "$DEST_CODEX"
  cp -r "$SRC_CODEX"/* "$DEST_CODEX/"
  echo "    Codex:    $DEST_CODEX/"
}

install_crush() {
  mkdir -p "$DEST_CRUSH"
  cleanup_managed_files "$DEST_CRUSH"
  for f in "$SRC_CRUSH"/*.md; do
    [[ -f "$f" ]] || continue
    cp "$f" "$DEST_CRUSH/$(basename "$f")"
    echo "    Crush:    $DEST_CRUSH/$(basename "$f")"
  done
  inject_loader_header "$HOME/.config/crush/CRUSH.md" "~/.config/crush/rules" "Crush Instructions"
  # Ensure crush.json has context_paths pointing to the rules and CRUSH.md
  local crush_json="$HOME/.config/crush/crush.json"
  local ctx_crush="~/.config/crush/CRUSH.md"
  local ctx_rules="~/.config/crush/rules/"
  if [[ -f "$crush_json" ]]; then
    # Add context_paths if not already present (idempotent)
    local needs_update=false
    if ! python3 -c "
import json, sys
with open('$crush_json') as f:
    cfg = json.load(f)
paths = cfg.get('options', {}).get('context_paths', [])
sys.exit(0 if '$ctx_crush' in paths and '$ctx_rules' in paths else 1)
" 2>/dev/null; then
      needs_update=true
    fi
    if [[ "$needs_update" == true ]]; then
      python3 <<'PY'
import json, os
path = os.path.expanduser("~/.config/crush/crush.json")
with open(path) as f:
    cfg = json.load(f)
opts = cfg.setdefault("options", {})
ctx = opts.setdefault("context_paths", [])
for p in ["~/.config/crush/CRUSH.md", "~/.config/crush/rules/"]:
    if p not in ctx:
        ctx.append(p)
with open(path, "w") as f:
    json.dump(cfg, f, indent=2)
    f.write("\n")
PY
      echo "    Config:   $crush_json (added context_paths)"
    fi
  else
    mkdir -p "$(dirname "$crush_json")"
    cat > "$crush_json" <<'JSON'
{
  "options": {
    "context_paths": [
      "~/.config/crush/CRUSH.md",
      "~/.config/crush/rules/"
    ]
  }
}
JSON
    echo "    Config:   $crush_json (created with context_paths)"
  fi
}

install_opencode() {
  mkdir -p "$DEST_OPENCODE"
  cleanup_managed_files "$DEST_OPENCODE"
  for f in "$SRC_OPENCODE"/*.md; do
    [[ -f "$f" ]] || continue
    cp "$f" "$DEST_OPENCODE/$(basename "$f")"
    echo "    OpenCode: $DEST_OPENCODE/$(basename "$f")"
  done
  inject_loader_header "$HOME/.config/opencode/AGENTS.md" "~/.config/opencode/rules" "Agent Instructions"
}

install_gemini() {
  mkdir -p "$DEST_GEMINI"
  cleanup_managed_files "$DEST_GEMINI"
  for f in "$SRC_GEMINI"/*.md; do
    [[ -f "$f" ]] || continue
    cp "$f" "$DEST_GEMINI/$(basename "$f")"
    echo "    Gemini:   $DEST_GEMINI/$(basename "$f")"
  done
  inject_loader_header "$HOME/.gemini/GEMINI.md" "~/.gemini/rules" "Gemini Instructions"
}

# --- List functions ---

list_claude() {
  echo "    Claude (~/.claude/rules/):"
  for f in "$SRC_CLAUDE"/*.md; do
    [[ -f "$f" ]] || continue
    local name
    name="$(basename "$f")"
    local dest="$DEST_CLAUDE/$name"
    local status="not found"
    [[ -f "$dest" ]] && status="installed"
    echo "      $dest  [$status]"
  done
}

list_cursor() {
  echo "    Cursor (~/.cursor/rules/):"
  for f in "$SRC_CURSOR"/*.mdc; do
    [[ -f "$f" ]] || continue
    local name
    name="$(basename "$f")"
    local dest="$DEST_CURSOR/$name"
    local status="not found"
    [[ -f "$dest" ]] && status="installed"
    echo "      $dest  [$status]"
  done
}

list_windsurf() {
  echo "    Windsurf (~/.windsurf/rules/):"
  for f in "$SRC_WINDSURF"/*.md; do
    [[ -f "$f" ]] || continue
    local name
    name="$(basename "$f")"
    local dest="$DEST_WINDSURF/$name"
    local status="not found"
    [[ -f "$dest" ]] && status="installed"
    echo "      $dest  [$status]"
  done
}

list_codex() {
  echo "    Codex (~/.codex/):"
  local dest="$DEST_CODEX/AGENTS.md"
  local status="not found"
  [[ -f "$dest" ]] && status="installed"
  echo "      $dest  [$status]"
}

list_crush() {
  echo "    Crush (~/.config/crush/rules/):"
  for f in "$SRC_CRUSH"/*.md; do
    [[ -f "$f" ]] || continue
    local name
    name="$(basename "$f")"
    local dest="$DEST_CRUSH/$name"
    local status="not found"
    [[ -f "$dest" ]] && status="installed"
    echo "      $dest  [$status]"
  done
  local crush_md="$HOME/.config/crush/CRUSH.md"
  local cmstatus="not found"
  [[ -f "$crush_md" ]] && cmstatus="installed"
  echo "      $crush_md  [$cmstatus]"
}

list_opencode() {
  echo "    OpenCode (~/.config/opencode/rules/):"
  for f in "$SRC_OPENCODE"/*.md; do
    [[ -f "$f" ]] || continue
    local name
    name="$(basename "$f")"
    local dest="$DEST_OPENCODE/$name"
    local status="not found"
    [[ -f "$dest" ]] && status="installed"
    echo "      $dest  [$status]"
  done
  local agents="$HOME/.config/opencode/AGENTS.md"
  local astatus="not found"
  [[ -f "$agents" ]] && astatus="installed"
  echo "      $agents  [$astatus]"
}

list_gemini() {
  echo "    Gemini (~/.gemini/rules/):"
  for f in "$SRC_GEMINI"/*.md; do
    [[ -f "$f" ]] || continue
    local name
    name="$(basename "$f")"
    local dest="$DEST_GEMINI/$name"
    local status="not found"
    [[ -f "$dest" ]] && status="installed"
    echo "      $dest  [$status]"
  done
  local gemini_md="$HOME/.gemini/GEMINI.md"
  local gmstatus="not found"
  [[ -f "$gemini_md" ]] && gmstatus="installed"
  echo "      $gemini_md  [$gmstatus]"
}

# --- Auto-detection ---

detect_editors() {
  local detected=()
  [[ -d "$HOME/.claude" ]] && detected+=("claude")
  [[ -d "$HOME/.cursor" ]] && detected+=("cursor")
  [[ -d "$HOME/.windsurf" || -d "$HOME/.codeium/windsurf" ]] && detected+=("windsurf")
  [[ -d "$HOME/.codex" ]] && detected+=("codex")
  [[ -d "$HOME/.config/crush" ]] && detected+=("crush")
  [[ -d "$HOME/.config/opencode" ]] && detected+=("opencode")
  [[ -d "$HOME/.gemini" ]] && detected+=("gemini")
  echo "${detected[@]}"
}

# --- Post-install notes ---

print_post_install() {
  echo ""
  echo "=== POST-INSTALL: REQUIRED IDE CONFIGURATION ==="
  echo ""
  if [[ "$SCAFFOLDED_MODE" == true ]]; then
    echo "  Voice: scaffolded (externalized reasoning with explicit labels)."
  else
    echo "  Voice: calibrated (internalized, peer-like prose)."
  fi
  echo "  Rich rules are installed as the universal default for all models."
  echo ""

  for target in "$@"; do
    case "$target" in
      claude)
        echo "  Claude Code"
        echo "    Rules installed to ~/.claude/rules/."
        echo "    CLAUDE.md loader header injected into ~/.claude/CLAUDE.md."
        echo "    No extra config needed."
        echo ""
        ;;
      cursor)
        echo "  Cursor (IMPORTANT)"
        echo "    1. Open Cursor Settings > Rules for AI"
        echo "    2. 00-init must load on every request (alwaysApply: true)."
        echo "    3. 01-router must load on every request (alwaysApply: true)."
        echo "    4. Expert rules (expert-*.mdc) are auto-attached by Cursor"
        echo "       when their description matches the conversation context."
        echo "    Files: ~/.cursor/rules/"
        echo ""
        ;;
      windsurf)
        echo "  Windsurf (IMPORTANT)"
        echo "    1. Open Windsurf > Customizations > Rules"
        echo "    2. 00-init.md has trigger: always — global runtime."
        echo "    3. 01-router.md has trigger: always — request triage."
        echo "    4. Expert rules use trigger: model_decision — Cascade reads"
        echo "       them automatically when the description matches."
        echo "    Files: ~/.windsurf/rules/"
        echo ""
        ;;
      codex)
        echo "  Codex"
        echo "    AGENTS.md and skills/ are installed to ~/.codex/."
        echo "    No extra config needed."
        echo ""
        ;;
      crush)
        echo "  Crush"
        echo "    Rules installed to ~/.config/crush/rules/."
        echo "    CRUSH.md loader header injected into ~/.config/crush/CRUSH.md."
        echo "    context_paths added to ~/.config/crush/crush.json."
        echo ""
        ;;
      opencode)
        echo "  OpenCode"
        echo "    Rules installed to ~/.config/opencode/rules/."
        echo "    AGENTS.md loader header injected into ~/.config/opencode/AGENTS.md."
        echo "    No extra config needed."
        echo ""
        ;;
      gemini)
        echo "  Gemini CLI"
        echo "    Rules installed to ~/.gemini/rules/."
        echo "    GEMINI.md @import block injected into ~/.gemini/GEMINI.md."
        echo "    Gemini CLI loads rules via native @file.md import syntax."
        echo "    No extra config needed."
        echo ""
        ;;
    esac
  done

  echo "  Tip: Run 'bash install-local.sh --list' to verify installed files."
  echo ""
}

# --- CLI parsing ---

TARGETS=()
DO_LIST=false
DEBUG_MODE=false
SCAFFOLDED_MODE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --claude)    TARGETS+=("claude"); shift ;;
    --cursor)    TARGETS+=("cursor"); shift ;;
    --windsurf)  TARGETS+=("windsurf"); shift ;;
    --codex)     TARGETS+=("codex"); shift ;;
    --crush)     TARGETS+=("crush"); shift ;;
    --opencode)  TARGETS+=("opencode"); shift ;;
    --gemini)    TARGETS+=("gemini"); shift ;;
    --all)       TARGETS=("claude" "cursor" "windsurf" "codex" "crush" "opencode" "gemini"); shift ;;
    --list)      DO_LIST=true; shift ;;
    --debug)     DEBUG_MODE=true; shift ;;
    --scaffolded) SCAFFOLDED_MODE=true; shift ;;
    --help|-h)
      echo "Usage: bash install-local.sh [options]"
      echo ""
      echo "Options:"
      echo "  --claude       Install rules for Claude Code"
      echo "  --cursor       Install rules for Cursor"
      echo "  --windsurf     Install rules for Windsurf"
      echo "  --codex        Install rules for Codex"
      echo "  --crush        Install rules for Crush"
      echo "  --opencode     Install rules for OpenCode"
      echo "  --gemini       Install rules for Gemini CLI"
      echo "  --all          Install for all editors"
      echo "  --list         List installed files and their status (no changes made)"
      echo "  --scaffolded   Use scaffolded voice (externalized reasoning with HYPOTHESIS/VERIFIED labels)"
      echo "                 Default is voice-calibrated (internalized, peer-like prose)."
      echo "  --debug        Build with debug routing output (Selected Expert / Reason / Confidence visible)"
      echo "  -h, --help     Show this help"
      echo ""
      echo "No flags = auto-detect installed editors."
      echo ""
      echo "Before running, generate the prompt files:"
      echo "  node scripts/build-prompt-system.mjs"
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      echo "Run: bash install-local.sh --help"
      exit 1
      ;;
  esac
done

# --- Build ---

if ($DEBUG_MODE || $SCAFFOLDED_MODE) && [[ -f "$REPO_DIR/scripts/build-prompt-system.mjs" ]]; then
  echo "--> Rebuilding prompt system (custom flags)..."
  BUILD_FLAGS=""
  $DEBUG_MODE && BUILD_FLAGS="$BUILD_FLAGS --debug"
  $SCAFFOLDED_MODE && BUILD_FLAGS="$BUILD_FLAGS --scaffolded"
  node "$REPO_DIR/scripts/build-prompt-system.mjs" $BUILD_FLAGS
elif [[ -d "$SRC_CLAUDE" ]] && ls "$SRC_CLAUDE"/*.md >/dev/null 2>&1; then
  echo "--> Compiled files found, skipping build."
elif [[ -f "$REPO_DIR/scripts/build-prompt-system.mjs" ]]; then
  echo "--> Building prompt system..."
  node "$REPO_DIR/scripts/build-prompt-system.mjs" --no-debug
else
  echo "ERROR: Generated files not found and no build script available."
  exit 1
fi
echo ""

# --- Auto-detect if no targets specified ---

if [[ ${#TARGETS[@]} -eq 0 ]]; then
  read -ra TARGETS <<< "$(detect_editors)"
fi

if [[ ${#TARGETS[@]} -eq 0 ]]; then
  echo "ERROR: No supported editors detected. Use --claude, --cursor, --windsurf, --codex, --crush, --opencode, or --gemini."
  exit 1
fi

# --- List path ---

if [[ "$DO_LIST" == true ]]; then
  echo "==> agent-historic installed files"
  echo "    Targets: ${TARGETS[*]}"
  echo ""
  for target in "${TARGETS[@]}"; do
    "list_${target}"
    echo ""
  done
  echo "==> No files were modified."
  exit 0
fi

# --- Install path ---

echo "==> agent-historic persona install"
echo "    Source:  $REPO_DIR"
echo "    Targets: ${TARGETS[*]}"
echo "    Style:   rich (universal default)"
echo ""

echo "--> Installing rules..."
for target in "${TARGETS[@]}"; do
  "install_${target}"
done

echo ""
echo "==> Done."

print_post_install "${TARGETS[@]}"
